export const reportGroups = [
  {key:'short_term_investments',label:'Investasi jangka pendek',type:'asset'},
  {key:'other_receivables',label:'Piutang lainnya',type:'asset'},
  {key:'prepaid_taxes',label:'Pajak dibayar di muka',type:'asset'},
  {key:'intangible_assets',label:'Aset takberwujud',type:'asset'},
  {key:'long_term_investments',label:'Investasi jangka panjang',type:'asset'},
  {key:'other_non_current_assets',label:'Aset tidak lancar lainnya',type:'asset'},
  { key:'current_assets',label:'Aset lancar',type:'asset' },{key:'non_current_assets',label:'Aset tidak lancar',type:'asset'},
  {key:'current_liabilities',label:'Liabilitas jangka pendek',type:'liability'},{key:'non_current_liabilities',label:'Liabilitas jangka panjang',type:'liability'},
  {key:'equity',label:'Ekuitas',type:'equity'},{key:'revenue',label:'Pendapatan',type:'revenue'},
  {key:'cogs',label:'Harga pokok',type:'cogs'},{key:'operating_expenses',label:'Beban operasional',type:'expense'},
  {key:'income_tax_expense',label:'Beban pajak penghasilan',type:'expense'},
  {key:'other_income',label:'Pendapatan lain',type:'other_income'},{key:'other_expenses',label:'Beban lain',type:'other_expense'},
  {key:'cash_and_bank',label:'Kas dan bank',type:'asset'},{key:'trade_receivables',label:'Piutang usaha',type:'asset'},
  {key:'inventory',label:'Persediaan',type:'asset'},{key:'prepaid_expenses',label:'Biaya dibayar di muka',type:'asset'},
  {key:'fixed_assets',label:'Aset tetap',type:'asset'},{key:'contra_assets',label:'Kontra aset',type:'asset'},
  {key:'trade_payables',label:'Utang usaha',type:'liability'},{key:'tax_payables',label:'Utang pajak',type:'liability'},
  {key:'operating_revenue',label:'Pendapatan usaha',type:'revenue'},{key:'cost_of_goods_sold',label:'Harga pokok penjualan',type:'cogs'},
  {key:'income_tax',label:'Pajak penghasilan',type:'expense'},
]
