import type { PoolConnection, RowDataPacket } from 'mysql2/promise'
import { stringify } from 'csv-stringify/sync'
import { db, transaction } from '../config/database'
import { ConflictError, NotFoundError, ValidationError } from '../utils/AppError'
import { PayrollFileService } from './PayrollFileService'
import { PayrollComponentService } from './PayrollComponentService'
import { AuditService } from './AuditService'
import { payrollDay, payrollProration, proratedMoney } from './payroll-proration'
import { readComponentSnapshot } from './payroll-component-calculation'
type Row=RowDataPacket&Record<string,any>
type Actor={userId:number;requestId?:string|null;ip?:string|null}
export class PayrollAutomationService{
 async assignments(companyId:number){return (await db.query<Row[]>('SELECT a.*,e.employee_number,e.name employee_name,c.name component_name,c.basis,c.channel FROM payroll_recurring_components a JOIN payroll_employees e ON e.id=a.employee_id JOIN payroll_components c ON c.id=a.component_id WHERE a.company_id=? ORDER BY e.name,c.name,a.effective_from',[companyId]))[0]}
 async saveAssignment(companyId:number,id:number|null,input:Record<string,any>,actor:Actor){return transaction(async cx=>{
  // Serialize assignment interval checks for the same employee.
  const [employees]=await cx.query<Row[]>('SELECT id FROM payroll_employees WHERE id=? AND company_id=? FOR UPDATE',[input.employee_id,companyId])
  const [components]=await cx.query<Row[]>('SELECT id,channel,is_active FROM payroll_components WHERE id=? AND company_id=? FOR SHARE',[input.component_id,companyId])
  if(!employees[0]||!components[0])throw new ValidationError('Pegawai dan komponen harus berasal dari perusahaan ini')
  if(!components[0].is_active&&input.is_active)throw new ValidationError('Komponen nonaktif tidak dapat dijadwalkan')
  if(components[0].channel.startsWith('external_'))throw new ValidationError('Pembayaran dari dokumen lain diisi manual agar nomor jurnal sumber diperiksa setiap periode')
  if(input.effective_to&&input.effective_to<input.effective_from)throw new ValidationError('Tanggal akhir sebelum tanggal mulai')
  let previous:Row|null=null
  if(id){const [rows]=await cx.query<Row[]>('SELECT * FROM payroll_recurring_components WHERE company_id=? AND id=? FOR UPDATE',[companyId,id]);previous=rows[0]??null;if(!previous)throw new NotFoundError('Penempatan komponen tidak ditemukan');if(Number(previous.version)!==Number(input.version))throw new ConflictError('Penempatan telah berubah. Muat ulang.')}
  if(input.is_active){const [overlap]=await cx.query<Row[]>("SELECT id FROM payroll_recurring_components WHERE company_id=? AND employee_id=? AND component_id=? AND is_active=TRUE AND id<>? AND effective_from<=COALESCE(?,'9999-12-31') AND COALESCE(effective_to,'9999-12-31')>=?",[companyId,input.employee_id,input.component_id,id??0,input.effective_to,input.effective_from]);if(overlap.length)throw new ConflictError('Jadwal komponen pegawai ini bertumpang tindih')}
  const fields=['employee_id','component_id','amount','effective_from','effective_to','prorate','is_active']
  if(id)await cx.query(`UPDATE payroll_recurring_components SET ${fields.map(k=>k+'=?').join(',')},version=version+1 WHERE id=? AND company_id=?`,[...fields.map(k=>input[k]??null),id,companyId]);else{const [r]=await cx.query<any>(`INSERT INTO payroll_recurring_components(company_id,${fields.join(',')}) VALUES(?,${fields.map(()=>'?').join(',')})`,[companyId,...fields.map(k=>input[k]??null)]);id=Number(r.insertId)}
  await new AuditService().log(cx,{companyId,userId:actor.userId,module:'payroll',action:'recurring_assignment_save',recordType:'payroll_recurring_component',recordId:id!,oldValue:previous,newValue:input,requestId:actor.requestId,ip:actor.ip});return{id}
 })}
 async configureRun(companyId:number,id:number,input:Record<string,any>,actor:Actor){return transaction(async cx=>{const run=await this.draft(cx,companyId,id);await cx.query('UPDATE payroll_runs SET proration_method=?,working_weekdays=?,prorate_bpjs=? WHERE id=?',[input.proration_method,input.working_weekdays,input.prorate_bpjs,id]);await new AuditService().log(cx,{companyId,userId:actor.userId,module:'payroll',action:'proration_policy',recordType:'payroll_run',recordId:id,oldValue:run,newValue:input});return{id}})}
 async applyRecurring(companyId:number,id:number,actor:Actor){return transaction(async cx=>{const run=await this.draft(cx,companyId,id);const count=await this.attachRecurring(cx,companyId,run);await new AuditService().log(cx,{companyId,userId:actor.userId,module:'payroll',action:'apply_recurring',recordType:'payroll_run',recordId:id,newValue:{added:count}});return{added:count}})}
 async attachRecurring(cx:PoolConnection,companyId:number,run:Row){
  const [entries]=await cx.query<Row[]>('SELECT * FROM payroll_entries WHERE run_id=? ORDER BY id',[run.id]);let added=0
  const [assignments]=await cx.query<Row[]>('SELECT a.*,c.effective_from component_from,c.effective_to component_to,c.basis FROM payroll_recurring_components a JOIN payroll_components c ON c.id=a.component_id WHERE a.company_id=? AND a.is_active=TRUE AND c.is_active=TRUE AND a.effective_from<=? AND (a.effective_to IS NULL OR a.effective_to>=?) ORDER BY a.id',[companyId,payrollDay(run.date_to),payrollDay(run.date_from)])
  const [allLines]=await cx.query<Row[]>('SELECT c.* FROM payroll_entry_components c JOIN payroll_entries e ON e.id=c.entry_id WHERE e.run_id=?',[run.id])
  const service=new PayrollComponentService()
  for(const e of entries){const lines=allLines.filter(l=>Number(l.entry_id)===Number(e.id));const inputs:any[]=lines.map(l=>({...l,tax_note:readComponentSnapshot(l.snapshot).tax_note,taxable_amount:Number(l.taxable_amount)===Number(l.amount)?null:l.taxable_amount}));const planned:any[]=[]
   for(const a of assignments.filter(a=>Number(a.employee_id)===Number(e.employee_id))){if(inputs.some(l=>Number(l.component_id)===Number(a.component_id)))continue
    const from=[payrollDay(run.date_from),payrollDay(a.effective_from),payrollDay(a.component_from),e.employment_from?payrollDay(e.employment_from):payrollDay(run.date_from)].sort().at(-1)!
    const to=[payrollDay(run.date_to),a.effective_to?payrollDay(a.effective_to):payrollDay(run.date_to),a.component_to?payrollDay(a.component_to):payrollDay(run.date_to),e.employment_to?payrollDay(e.employment_to):payrollDay(run.date_to)].sort()[0]!
    if(from>to)continue
    const fraction=payrollProration(payrollDay(run.date_from),payrollDay(run.date_to),from,to,run.proration_method==='working_days'?'working_days':'calendar',run.working_weekdays)
    const amount=a.prorate?proratedMoney(a.amount,fraction.ratio):Number(a.amount)
    inputs.push({component_id:a.component_id,amount,taxable_amount:null,recurring_metadata:{assignment_id:Number(a.id),base_amount:Number(a.amount),prorate:Boolean(a.prorate),from,to}});planned.push(a)
   }
   if(planned.length){await service.replaceLines(cx,companyId,run,e,inputs);for(const a of planned){await cx.query('UPDATE payroll_entry_components SET recurring_assignment_id=? WHERE entry_id=? AND component_id=?',[a.id,e.id,a.component_id]);added++}}
  }return added
 }
 template(period='2026-10'){return{content:Buffer.from(stringify([{nomor_pegawai:'EMP-001',tanggal:period+'-01',status:'hadir',jam_lembur:0,keterangan:''}],{header:true,delimiter:';',bom:true})),contentType:'text/csv; charset=utf-8',filename:'template-absensi-harian.csv'}}
 async preview(companyId:number,id:number,file:File){const [runs]=await db.query<Row[]>('SELECT * FROM payroll_runs WHERE id=? AND company_id=?',[id,companyId]);const run=runs[0];if(!run)throw new NotFoundError('Payroll tidak ditemukan');if(run.status!=='draft')throw new ConflictError('Absensi hanya dapat diimpor saat Draft');const [employees]=await db.query<Row[]>('SELECT e.*,m.employee_number,m.name FROM payroll_entries e JOIN payroll_employees m ON m.id=e.employee_id WHERE e.run_id=?',[id]);const raw=await new PayrollFileService().readFile(file);if(!raw.length||raw.length>50000)throw new ValidationError('File harus berisi 1 sampai 50.000 baris');const seen=new Set<string>();const rows=raw.map((r,index)=>{
  const values=Object.fromEntries(Object.entries(r).map(([k,v])=>[k.trim().toLowerCase(),v]));const number=String(values.nomor_pegawai??values.employee_number??'').trim();const e=employees.find(e=>e.employee_number===number);const date=values.tanggal instanceof Date?payrollDay(values.tanggal):String(values.tanggal??'').trim();const status=String(values.status??'').trim().toLowerCase();const overtime=Number(String(values.jam_lembur??0).replace(',','.'));const notes=String(values.keterangan??'').trim();const errors:string[]=[]
  if(!e)errors.push('Pegawai tidak ada pada payroll ini');if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||Number.isNaN(Date.parse(date))||new Date(date+'T00:00:00Z').toISOString().slice(0,10)!==date)errors.push('Tanggal harus YYYY-MM-DD yang valid');else if(date<payrollDay(run.date_from)||date>payrollDay(run.date_to)||e?.employment_from&&date<payrollDay(e.employment_from)||e?.employment_to&&date>payrollDay(e.employment_to))errors.push('Tanggal di luar periode / masa kerja');if(!['hadir','cuti','sakit','absen','libur'].includes(status))errors.push('Status: hadir, cuti, sakit, absen, atau libur');if(!Number.isFinite(overtime)||overtime<0||overtime>24)errors.push('Jam lembur harus 0–24');if(notes.length>500)errors.push('Keterangan maksimal 500 karakter');const key=number+'|'+date;if(seen.has(key))errors.push('Pegawai dan tanggal duplikat di file');seen.add(key);return{source_row:index+2,employee_number:number,employee_name:e?.name,entry_id:e?.id,date,status,overtime_hours:overtime,notes,errors}
 });return{filename:file.name,total_rows:rows.length,invalid_rows:rows.filter(r=>r.errors.length).length,valid_rows:rows.filter(r=>!r.errors.length).length,rows}}
 async apply(companyId:number,id:number,file:File,actor:Actor){const preview=await this.preview(companyId,id,file);if(preview.invalid_rows)throw new ValidationError('Perbaiki seluruh baris absensi yang salah sebelum impor');return transaction(async cx=>{
  const run=await this.draft(cx,companyId,id);const entries=new Set<number>()
  for(const row of preview.rows){entries.add(Number(row.entry_id));await cx.query('INSERT INTO payroll_attendance_days(entry_id,attendance_date,status,overtime_hours,notes,imported_by) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE status=VALUES(status),overtime_hours=VALUES(overtime_hours),notes=VALUES(notes),imported_by=VALUES(imported_by)',[row.entry_id,row.date,row.status,row.overtime_hours,row.notes,actor.userId])}
  for(const entryId of entries){const [sums]=await cx.query<Row[]>("SELECT SUM(status<>'libur') planned_days,SUM(status='hadir') present_days,SUM(status='cuti') paid_leave_days,SUM(status='sakit') sick_days,SUM(status='absen') absent_days,SUM(overtime_hours) overtime_hours FROM payroll_attendance_days WHERE entry_id=?",[entryId]);const sum=sums[0]!,fields=['planned_days','present_days','paid_leave_days','sick_days','absent_days','overtime_hours'];await cx.query(`UPDATE payroll_entries SET ${fields.map(k=>k+'=?').join(',')} WHERE id=?`,[...fields.map(k=>sum[k]),entryId]);await this.refreshLines(cx,companyId,run,entryId)}
  await new AuditService().log(cx,{companyId,userId:actor.userId,module:'payroll',action:'attendance_import',recordType:'payroll_run',recordId:id,newValue:{filename:file.name,rows:preview.rows.length,employees:entries.size},requestId:actor.requestId,ip:actor.ip});return{imported_rows:preview.rows.length,employees:entries.size}
 })}
 async refreshLines(cx:PoolConnection,companyId:number,run:Row,entryId:number){const [entries]=await cx.query<Row[]>('SELECT * FROM payroll_entries WHERE id=? AND run_id=?',[entryId,run.id]);const [lines]=await cx.query<Row[]>('SELECT * FROM payroll_entry_components WHERE entry_id=?',[entryId]);if(lines.length)await new PayrollComponentService().replaceLines(cx,companyId,run,entries[0]!,lines.map(l=>({...l,tax_note:readComponentSnapshot(l.snapshot).tax_note,taxable_amount:Number(l.taxable_amount)===Number(l.amount)?null:l.taxable_amount})))}
 private async draft(cx:PoolConnection,companyId:number,id:number){const [rows]=await cx.query<Row[]>('SELECT * FROM payroll_runs WHERE id=? AND company_id=? FOR UPDATE',[id,companyId]);if(!rows[0])throw new NotFoundError('Payroll tidak ditemukan');if(rows[0].status!=='draft')throw new ConflictError('Hanya payroll Draft yang dapat diubah');return rows[0]}
}
