import assert from 'node:assert/strict'
import { db, transaction } from '../config/database'
import { PayrollService } from '../services/PayrollService'
import { PayrollComponentService } from '../services/PayrollComponentService'
import { PostingService } from '../services/PostingService'
export async function verifyPayrollComponents(userId:number,approverId:number,ids:Record<string,number>){
 assert.match(String(process.env.DB_NAME),/^finora_verify_\d+_\d+$/)
 const actor={userId}, approver={userId:approverId}, payroll=new PayrollService(), master=new PayrollComponentService(), posting=new PostingService()
 await db.execute(`INSERT INTO payroll_policies(company_id,effective_from,created_by,salary_expense_account_id,employer_bpjs_expense_account_id,payroll_payable_account_id,bpjs_payable_account_id,pph21_payable_account_id,employee_loan_account_id,other_deduction_account_id) VALUES(1,'2026-04-01',?,?,?,?,?,?,?,?)`,[userId,ids['6100'],ids['6100'],ids['2101'],ids['2202'],ids['2202'],ids['1101'],ids['2202']])
 await db.execute("INSERT INTO payroll_employees(company_id,employee_number,name,hire_date,termination_date,ptkp_status,ter_category,basic_salary,fixed_allowance,bank_account_number,created_by,is_active) VALUES(1,'COMP-EMP','Components employee','2026-04-01','2026-04-30','TK/0','A',6000000,500000,'99990001',?,FALSE)",[userId])
 const common={kind:'earning',channel:'payroll',basis:'nominal',rate:0,taxable:true,bpjs_base:false,expense_account_id:ids['6400'],contra_account_id:null,effective_from:'2026-04-01',effective_to:null,policy_reference:'Verified component policy',is_active:true}
 await db.execute("UPDATE payroll_policies SET health_employer_expense_account_id=?,employment_employer_expense_account_id=? WHERE company_id=1 AND effective_from='2026-04-01'",[ids['6400'],ids['6100']])
 const meal=await master.save(1,null,{...common,code:'MEAL-DAY',name:'Manual meal allowance'},actor)
 const benefit=await master.save(1,null,{...common,code:'MEAL-NONCASH',name:'Noncash meals',channel:'noncash',contra_account_id:ids['2101']},actor)
 const external=await master.save(1,null,{...common,code:'MEAL-VENDOR',name:'Vendor meals',channel:'external_noncash',taxable:false},actor)
 const deduction=await master.save(1,null,{...common,code:'OTHER-DEDUCTION',name:'Other deduction',kind:'deduction',taxable:false,expense_account_id:null,contra_account_id:ids['2202']},actor)
 const source=await transaction(cx=>posting.createPostedJournal(cx,{companyId:1,sourceType:'benefit_test',sourceId:99001,date:'2026-04-10',reference:'MEAL-VENDOR-TEST',description:'Vendor expense',lines:[{accountId:ids['6400']!,debit:600000,credit:0},{accountId:ids['2101']!,debit:0,credit:600000}],context:actor}))
 const [sourceRows]=await db.query<any[]>('SELECT journal_number FROM journals WHERE id=?',[source])
 const run:any=await payroll.createRun(1,{period:'2026-04',pay_date:'2026-04-30'},actor)
 const runId=Number(run.run.id),entryId=Number(run.entries[0].id)
 const components=[{component_id:meal.id,amount:1100000},{component_id:benefit.id,amount:2500000,taxable_amount:500000,tax_note:'Verified partial tax treatment'},{component_id:external.id,amount:600000,source_reference:sourceRows[0].journal_number},{component_id:deduction.id,amount:100000}]
 await payroll.updateEntry(1,runId,entryId,{reimbursement:100000,reimbursement_taxable:false,absence_deduction:100000,absence_reduces_tax:true,custom_components:components},actor)
 const before:any=await payroll.detail(1,runId)
 assert.equal(Number(before.entries[0].custom_components[0].amount),1100000)
 await master.save(1,meal.id,{...common,code:'MEAL-DAY',name:'Changed meal policy',version:1},actor)
 await assert.rejects(()=>master.save(1,meal.id,{...common,code:'MEAL-DAY',name:'Stale edit',version:1},actor))
 const calculated:any=await payroll.calculate(1,runId), e=calculated.entries[0]
 assert.equal(Number(e.custom_earnings),4200000);assert.equal(Number(e.gross_earnings),10800000)
 assert.equal(Number(e.cash_earnings),7700000);assert.equal(Number(e.noncash_earnings),3100000);assert.equal(Number(e.external_earnings),600000)
 assert.equal(Number(e.bpjs_salary_base),6500000)
 assert.equal(Number(e.take_home_pay),7700000-200000-Number(e.employee_bpjs)-Number(e.pph21))
 assert.equal(Number(e.taxable_gross),8000000+Number(e.bpjs_health_employer)+Number(e.bpjs_jkk_employer)+Number(e.bpjs_jkm_employer))
 assert.equal(Number(e.custom_components[0].snapshot.rate),0)
 await assert.rejects(()=>payroll.updateEntry(1,runId,entryId,{bonus:1},actor))
 await payroll.reopen(1,runId,'Verify allocation validation',actor)
 assert.equal(Number(e.paid_basic_salary),6000000);assert.equal(Number(e.proration_ratio),1)
 await assert.rejects(()=>payroll.updateEntry(1,runId,entryId,{custom_components:components.map(c=>c.component_id===external.id?{...c,amount:600001}:c)},actor))
 await assert.rejects(()=>payroll.updateEntry(1,runId,entryId,{custom_components:[components[0],components[0]]},actor))
 await assert.rejects(()=>payroll.updateEntry(999999,runId,entryId,{bonus:1},actor))
 // Competing allocations in different payroll runs must read the latest committed source balance.
 await db.execute("INSERT INTO payroll_employees(company_id,employee_number,name,hire_date,termination_date,ptkp_status,ter_category,basic_salary,fixed_allowance,bank_account_number,created_by) VALUES(1,'COMP-RACE-A','Race A','2026-05-01','2026-06-30','TK/0','A',0,0,'99990002',?),(1,'COMP-RACE-B','Race B','2026-05-01','2026-06-30','TK/0','A',0,0,'99990003',?)",[userId,userId])
 const raceSource=await transaction(cx=>posting.createPostedJournal(cx,{companyId:1,sourceType:'benefit_race',sourceId:99002,date:'2026-05-10',reference:'MEAL-RACE',description:'Concurrent benefits',lines:[{accountId:ids['6400']!,debit:300000,credit:0},{accountId:ids['2101']!,debit:0,credit:300000}],context:actor}))
 const [raceJournals]=await db.query<any[]>('SELECT journal_number FROM journals WHERE id=?',[raceSource])
 const may:any=await payroll.createRun(1,{period:'2026-05',pay_date:'2026-05-31'},actor),june:any=await payroll.createRun(1,{period:'2026-06',pay_date:'2026-06-30'},actor)
 const races=await Promise.allSettled([payroll.updateEntry(1,may.run.id,may.entries[0].id,{custom_components:[{component_id:external.id,amount:300000,source_reference:raceJournals[0].journal_number}]},actor),payroll.updateEntry(1,june.run.id,june.entries[1].id,{custom_components:[{component_id:external.id,amount:300000,source_reference:raceJournals[0].journal_number}]},actor)])
 assert.equal(races.filter(r=>r.status==='fulfilled').length,1)
 const [allocated]=await db.query<any[]>('SELECT SUM(amount) amount FROM payroll_entry_components WHERE source_journal_id=?',[raceSource])
 assert.equal(Number(allocated[0].amount),300000)
 await payroll.calculate(1,runId)
 await payroll.approve(1,runId,approver)
 const posted:any=await payroll.post(1,runId,actor)
 const [bpjsLines]=await db.query<any[]>("SELECT account_id,debit,description FROM journal_lines WHERE journal_id=? AND description LIKE 'BPJS %perusahaan%'",[posted.run.journal_id])
 assert.equal(bpjsLines.length,2)
 assert.equal(Number(bpjsLines.find(l=>l.description==='BPJS Kesehatan perusahaan').account_id),ids['6400'])
 assert.equal(Number(bpjsLines.find(l=>l.description==='BPJS Kesehatan perusahaan').debit),Number(e.bpjs_health_employer))
 assert.equal(Number(bpjsLines.find(l=>l.description.startsWith('BPJS Ketenagakerjaan')).account_id),ids['6100'])
 assert.ok(posted.expense_accounts.every((a:any)=>Math.abs(a.difference)<0.01))
 assert.equal(posted.reconciliation.ledger.matched,true)
 assert.equal(posted.reconciliation.ledger.external_amount,600000)
 const [expense]=await db.query<any[]>("SELECT SUM(l.debit-l.credit) amount FROM journal_lines l JOIN accounts a ON a.id=l.account_id WHERE journal_id=? AND a.account_type='expense'",[posted.run.journal_id])
 assert.equal(Number(expense[0].amount),Number(posted.run.total_company_cost)-600000)
 await assert.rejects(()=>transaction(cx=>posting.reversePostedJournal(cx,{companyId:1,journalId:source,date:'2026-04-30',reason:'Cannot reverse linked benefit',context:actor})))
 await assert.rejects(()=>payroll.unlock(1,runId,'Before locking',actor))
 // Fixture represents an already paid run; unlock must retain both journal references and totals.
 await db.execute("UPDATE payroll_runs SET status='paid',payment_journal_id=? WHERE id=?",[source,runId])
 await payroll.lock(1,runId,actor)
 await assert.rejects(()=>payroll.unlock(999999,runId,'Wrong company',actor))
 await assert.rejects(()=>payroll.unlock(1,runId,'',actor))
 const unlocked:any=await payroll.unlock(1,runId,'Review reconciliation',actor)
 assert.equal(unlocked.run.status,'paid');assert.equal(unlocked.run.journal_id,posted.run.journal_id)
 assert.equal(Number(unlocked.run.payment_journal_id),source)
 assert.equal(Number(unlocked.run.total_company_cost),Number(posted.run.total_company_cost))
 await assert.rejects(()=>payroll.unlock(1,runId,'Repeated unlock',actor))
 await payroll.lock(1,runId,actor)
 console.log('PASS Payroll components: manual amounts, noncash, external GL sources, split expenses, tax bases, immutable snapshots, stale edits, over-allocation, tenant isolation, concurrent source allocations and balanced posting')
}
