import assert from 'node:assert/strict'
import { db } from '../config/database'
import { RoleService } from '../services/RoleService'
import { SystemUserService } from '../services/SystemUserService'
import { AuthService } from '../services/AuthService'
import { createUserSchema, updateRoleSchema } from '../validators/system.validator'

export async function verifyUserAccess(userId: number) {
  assert.match(String(process.env.DB_NAME), /^finora_verify_\d+_\d+$/)
  const actor = { id:userId, companyId:1, roles:['super-admin'] }
  const users = new SystemUserService(), roles = new RoleService(), auth = new AuthService()
  const [permissions] = await db.query<any[]>("SELECT id,slug FROM permissions WHERE slug='accounts.view'")
  assert.ok(permissions[0])
  const role = await roles.create(actor,{name:'Access verifier',slug:'access-verifier',is_active:true,permission_ids:[permissions[0].id]})
  const roleId = Number((role as any).id)
  const empty = await roles.create(actor,{name:'Empty verifier',slug:'empty-verifier',is_active:true,permission_ids:[]})
  const input = createUserSchema.parse({ name:'New user',email:' NEW.USER@VERIFY.LOCAL ',password:'VerifyPass123',status:'active',role_ids:[roleId] })
  assert.equal(input.email,'new.user@verify.local')
  const user = await users.create(actor,input)
  assert.ok(user)
  const id = Number(user!.id)
  const login = await auth.login(input.email,input.password)
  assert.equal(login.user.id,id)
  assert.equal(login.user.companyId,1)
  assert.deepEqual(login.user.roles,['access-verifier'])
  assert.deepEqual(login.user.permissions,['accounts.view'])
  assert.equal(Number((await roles.list(1,{page:'1',limit:'100'})).rows.find((r:any)=>Number(r.id)===roleId)?.permission_count),1)
  await assert.rejects(()=>users.create(actor,{...input,email:'empty@verify.local',role_ids:[Number((empty as any).id)]}),/hak akses/)
  await assert.rejects(()=>users.create(actor,{...input,email:'invalid-role@verify.local',role_ids:[999999999]}),/tidak valid/)
  await assert.rejects(()=>users.update(actor,id,{name:'Should rollback',role_ids:[999999999]}),/tidak valid/)
  assert.equal((await users.get(id,1) as any).name,'New user')
  await assert.rejects(()=>roles.update(actor,roleId,updateRoleSchema.parse({name:'Should rollback',permission_ids:[999999999]})),/tidak valid/)
  assert.equal((await roles.get(roleId,1) as any).name,'Access verifier')
  await users.update(actor,id,{name:'Updated user',password:'NewVerify123',status:'inactive',role_ids:[roleId]})
  await assert.rejects(()=>auth.login(input.email,'NewVerify123'))
  await users.setStatus(actor,id,'active')
  assert.equal((await auth.login(input.email,'NewVerify123')).user.id,id)
  await assert.rejects(()=>auth.login(input.email,input.password))
  await assert.rejects(()=>users.assignRoles(actor,id,[]),/hak akses/)
  await assert.rejects(()=>users.get(id,999999))
  await assert.rejects(()=>users.create(actor,input))
  await roles.update(actor,roleId,updateRoleSchema.parse({name:'Updated role',permission_ids:[permissions[0].id],is_active:true}))
  assert.equal((await roles.get(roleId,1) as any).permissions.length,1)
  await roles.update(actor,roleId,updateRoleSchema.parse({description:'Metadata only'}))
  assert.equal((await roles.get(roleId,1) as any).permissions.length,1)
  const { createApp } = await import('../config/app')
  const { authMiddleware } = await import('../middleware/auth.middleware')
  const { errorHandler } = await import('../middleware/error.middleware')
  const { signToken } = await import('../utils/token')
  const { default: userRoutes } = await import('../routes/users.routes')
  const { AuthController } = await import('../controllers/AuthController')
  const api = createApp()
  api.onError(errorHandler)
  api.post('/login',new AuthController().login)
  api.use('/users/*',authMiddleware)
  api.route('/users',userRoutes)
  const { default: preferences } = await import('../routes/preferences.routes')
  api.use('/preferences/*',authMiddleware)
  api.route('/preferences',preferences)
  const request = (path:string,body:unknown,token:string) => api.request(path,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(body)})
  const adminToken = signToken({id:userId,companyId:1})
  await new (await import('../services/AuthSessionService')).AuthSessionService().register(adminToken,userId,1,'Integration admin')
  const httpInput={...input,email:'http-user@verify.local'}
  assert.equal((await request('/users',httpInput,adminToken)).status,201)
  assert.equal((await request('/users',httpInput,adminToken)).status,409)
  assert.equal((await request('/users',{...input,email:'bad-password@verify.local',password:'abcdefgh'},adminToken)).status,422)
  const signedIn=await request('/login',{email:httpInput.email,password:input.password},'')
  assert.equal(signedIn.status,200)
  const payload=await signedIn.json() as any
  assert.ok(payload.data.token)
  assert.equal((await request('/users',{...input,email:'unauthorized@verify.local'},payload.data.token)).status,403)
  const preferenceRequest = (value:unknown,token:string) => api.request('/preferences/interface-language',{method:'PUT',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(value)})
  const preferenceRead = async(token:string) => (await api.request('/preferences/interface-language',{headers:{Authorization:`Bearer ${token}`}})).json() as Promise<any>
  assert.equal((await preferenceRequest(['en-US'],payload.data.token)).status,200)
  assert.equal((await preferenceRequest(['zh-CN'],adminToken)).status,200)
  assert.deepEqual((await preferenceRead(payload.data.token)).data,['en-US'])
  assert.deepEqual((await preferenceRead(adminToken)).data,['zh-CN'])
  assert.equal((await preferenceRequest(['fr-FR'],payload.data.token)).status,422)
  assert.equal((await preferenceRequest(['en-US','zh-CN'],payload.data.token)).status,422)
  assert.deepEqual((await preferenceRead(payload.data.token)).data,['en-US'])
  const {AuthSessionService}=await import('../services/AuthSessionService')
  const sessions=new AuthSessionService(),httpUserId=Number(payload.data.user.id)
  const firstSession=await sessions.validate(payload.data.token,httpUserId,1)
  const second=await auth.login(httpInput.email,input.password,{device:'Session verifier'})
  assert.notEqual(second.token,payload.data.token)
  const secondSession=await sessions.validate(second.token,httpUserId,1)
  assert.equal((await sessions.list(httpUserId,1,secondSession)).length,2)
  await assert.rejects(()=>sessions.revoke(userId,1,firstSession))
  await sessions.revoke(httpUserId,1,firstSession)
  assert.equal((await preferenceRequest(['en-US'],payload.data.token)).status,401)
  assert.equal((await preferenceRequest(['en-US'],second.token)).status,200)
  await db.execute('UPDATE auth_sessions SET last_seen_at=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 2 MINUTE) WHERE id=?',[secondSession])
  await db.execute("INSERT INTO settings(company_id,setting_key,setting_value,value_type,category) VALUES(1,'security.session_timeout_minutes','1','number','security') ON DUPLICATE KEY UPDATE setting_value='1'")
  await assert.rejects(()=>sessions.validate(second.token,httpUserId,1))
  const third=await auth.login(httpInput.email,input.password)
  await users.resetPassword(actor,httpUserId,'ResetVerify123')
  await assert.rejects(()=>sessions.validate(third.token,httpUserId,1))
  const fourth=await auth.login(httpInput.email,'ResetVerify123')
  await sessions.revoke(httpUserId,1,'',true)
  await assert.rejects(()=>sessions.validate(fourth.token,httpUserId,1))
  await db.execute("INSERT INTO settings(company_id,setting_key,setting_value,value_type,category) VALUES(1,'security.max_login_attempts','2','number','security') ON DUPLICATE KEY UPDATE setting_value='2'")
  await assert.rejects(()=>auth.login(httpInput.email,'WrongPass123'))
  await assert.rejects(()=>auth.login(httpInput.email,'WrongPass123'))
  await assert.rejects(()=>auth.login(httpInput.email,'ResetVerify123'),(e:any)=>e.status===429)
  await db.execute('UPDATE users SET last_failed_login_at=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 16 MINUTE) WHERE id=?',[httpUserId])
  const fifth=await auth.login(httpInput.email,'ResetVerify123')
  assert.ok(fifth.token)
  await db.execute("UPDATE settings SET setting_value='480' WHERE company_id=1 AND setting_key='security.session_timeout_minutes'")
  await db.execute("UPDATE settings SET setting_value='5' WHERE company_id=1 AND setting_key='security.max_login_attempts'")
  const logoutApi=createApp();logoutApi.onError(errorHandler);logoutApi.use('*',authMiddleware)
  logoutApi.post('/logout',new AuthController().logout);logoutApi.get('/me',new AuthController().me)
  const headers={Authorization:`Bearer ${fifth.token}`}
  assert.equal((await logoutApi.request('/me',{headers})).status,200)
  assert.equal((await logoutApi.request('/logout',{method:'POST',headers})).status,200)
  assert.equal((await logoutApi.request('/me',{headers})).status,401)
  const {loginRateLimit}=await import('../middleware/login-rate-limit.middleware')
  const limitApi=createApp();limitApi.onError(errorHandler);limitApi.post('/login',loginRateLimit,c=>c.json({ok:true}))
  for(let n=0;n<30;n++)assert.equal((await limitApi.request('/login',{method:'POST',headers:{'x-forwarded-for':`spoof-${n}`}})).status,200)
  assert.equal((await limitApi.request('/login',{method:'POST',headers:{'x-forwarded-for':'another-spoof'}})).status,429)
  const previousOperators=process.env.PLATFORM_OPERATOR_USER_IDS,previousDatabases=process.env.PLATFORM_MONITORED_DATABASES
  const {default:platformRoutes}=await import('../routes/platform.routes')
  const platformApi=createApp();platformApi.onError(errorHandler);platformApi.use('*',authMiddleware);platformApi.route('/platform',platformRoutes)
  try{
   process.env.PLATFORM_OPERATOR_USER_IDS='';process.env.PLATFORM_MONITORED_DATABASES='missing_owner_verify_database,invalid-name'
   assert.equal((await platformApi.request('/platform/overview',{headers:{Authorization:`Bearer ${adminToken}`}})).status,403)
   process.env.PLATFORM_OPERATOR_USER_IDS=String(userId)
   const result=await platformApi.request('/platform/overview',{headers:{Authorization:`Bearer ${adminToken}`}})
   assert.equal(result.status,200)
   const overview:any=await result.json();assert.ok(overview.data.summary.companies>=1);assert.equal(overview.data.databases.find((d:any)=>d.current).available,true)
   assert.equal(overview.data.databases.find((d:any)=>d.name==='missing_owner_verify_database').available,false)
   assert.equal(overview.data.databases.some((d:any)=>d.name==='invalid-name'),false)
   const otherLogin=await auth.login(httpInput.email,'ResetVerify123')
   assert.equal((await platformApi.request('/platform/companies/1',{headers:{Authorization:`Bearer ${otherLogin.token}`}})).status,403)
   const companyResult=await platformApi.request('/platform/companies/1',{headers:{Authorization:`Bearer ${adminToken}`}})
   assert.equal(companyResult.status,200);assert.ok((await companyResult.json() as any).data.counts.journals>=0)
   assert.equal((await platformApi.request('/platform/companies/999999999',{headers:{Authorization:`Bearer ${adminToken}`}})).status,404)
   assert.equal((await platformApi.request('/platform/overview?page=0',{headers:{Authorization:`Bearer ${adminToken}`}})).status,422)
   assert.equal((await platformApi.request('/platform/overview')).status,401)
   const errorIds:number[]=[]
   for(let n=0;n<30;n++){const [r]=await db.execute<any>("INSERT INTO error_logs(company_id,level,category,message,error_code,path,method) VALUES(1,'error','alert_verify',?,'VERIFY','/verify?token=SUPERSECRET','GET')",["token=SUPERSECRET 'private value'"]);errorIds.push(Number(r.insertId))}
   const ownerHeaders={Authorization:`Bearer ${adminToken}`}
   const alertResponse=await platformApi.request('/platform/alerts/errors',{headers:ownerHeaders})
   assert.equal(alertResponse.status,200);const alertBody:any=await alertResponse.json();assert.equal(alertBody.data.rows.length,25);assert.ok(alertBody.data.total>=30)
   assert.equal(JSON.stringify(alertBody).includes('SUPERSECRET'),false)
   assert.equal((await platformApi.request('/platform/alerts/errors?page=2',{headers:ownerHeaders})).status,200)
   assert.equal((await platformApi.request('/platform/alerts/errors',{headers:{Authorization:`Bearer ${otherLogin.token}`}})).status,403)
   const resolveOptions={method:'POST',headers:{...ownerHeaders,'Content-Type':'application/json'},body:JSON.stringify({note:'Verified fix applied'})}
   assert.equal((await platformApi.request(`/platform/errors/${errorIds[29]}/resolve`,resolveOptions)).status,200)
   assert.equal((await platformApi.request(`/platform/errors/${errorIds[29]}/resolve`,resolveOptions)).status,409)
   const resolved:any=await (await platformApi.request('/platform/alerts/errors?status=resolved',{headers:ownerHeaders})).json()
   assert.ok(resolved.data.rows.some((r:any)=>Number(r.id)===errorIds[29]))
   assert.equal((await platformApi.request('/platform/alerts/not-real',{headers:ownerHeaders})).status,422)
   assert.equal((await platformApi.request('/platform/alerts/errors?page=0',{headers:ownerHeaders})).status,422)
   const [auditRows]=await db.query<any[]>("SELECT COUNT(*) n FROM audit_logs WHERE module='platform' AND action='resolve_error' AND record_id=?",[errorIds[29]]);assert.equal(Number(auditRows[0].n),1)
   console.log('PASS Platform alerts: detail pagination, owner-only access, message redaction, resolution audit, stale-resolution rejection and validation')

  }finally{if(previousOperators===undefined)delete process.env.PLATFORM_OPERATOR_USER_IDS;else process.env.PLATFORM_OPERATOR_USER_IDS=previousOperators;if(previousDatabases===undefined)delete process.env.PLATFORM_MONITORED_DATABASES;else process.env.PLATFORM_MONITORED_DATABASES=previousDatabases}
  console.log('PASS Platform dashboard: owner allowlist, tenant admin denial, metadata allowlist, company drilldown, validation and anonymous denial')
  console.log('PASS Session security: unique tokens, owner-scoped revocation, idle timeout, password reset, all-device logout, configured login limit and cooldown')
  console.log('PASS Language preferences: saved per user, separate administrators, persisted reads and rejection of unsupported locales')
  console.log('PASS User access: creation, normalized email, login, role counts, empty-access rejection, atomic rollback, password reset, inactive login and tenant isolation')
}
