export const migration = {
  name: '002_master',
  up: async (db: { query: (sql: string) => Promise<unknown> }) =>
    db.query(`
CREATE TABLE customers(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  code VARCHAR(30) NOT NULL,
  name VARCHAR(191) NOT NULL,
  tax_number VARCHAR(50),
  email VARCHAR(191),
  phone VARCHAR(50),
  address TEXT,
  city VARCHAR(100),
  credit_limit DECIMAL(20,
  2) NOT NULL DEFAULT 0,
  payment_term_days INT NOT NULL DEFAULT 0,
  receivable_account_id BIGINT UNSIGNED,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  UNIQUE KEY uq_customer(company_id,
  code),
  FOREIGN KEY(company_id) REFERENCES companies(id),
  FOREIGN KEY(receivable_account_id) REFERENCES accounts(id),
  INDEX idx_customer_name(company_id,
  name,
  is_active)) ENGINE=InnoDB;
CREATE TABLE suppliers(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  code VARCHAR(30) NOT NULL,
  name VARCHAR(191) NOT NULL,
  tax_number VARCHAR(50),
  email VARCHAR(191),
  phone VARCHAR(50),
  address TEXT,
  city VARCHAR(100),
  payment_term_days INT NOT NULL DEFAULT 0,
  payable_account_id BIGINT UNSIGNED,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  UNIQUE KEY uq_supplier(company_id,
  code),
  FOREIGN KEY(company_id) REFERENCES companies(id),
  FOREIGN KEY(payable_account_id) REFERENCES accounts(id)) ENGINE=InnoDB;
CREATE TABLE units(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  code VARCHAR(30) NOT NULL,
  name VARCHAR(100) NOT NULL,
  symbol VARCHAR(20) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE KEY uq_unit(company_id,
  code),
  FOREIGN KEY(company_id) REFERENCES companies(id)) ENGINE=InnoDB;
CREATE TABLE warehouses(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  code VARCHAR(30) NOT NULL,
  name VARCHAR(150) NOT NULL,
  address TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_warehouse(company_id,
  code),
  FOREIGN KEY(company_id) REFERENCES companies(id)) ENGINE=InnoDB;
CREATE TABLE tax_codes(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  code VARCHAR(30) NOT NULL,
  name VARCHAR(100) NOT NULL,
  tax_type ENUM('vat',
  'withholding',
  'other') NOT NULL,
  rate DECIMAL(8,
  4) NOT NULL,
  input_tax_account_id BIGINT UNSIGNED,
  output_tax_account_id BIGINT UNSIGNED,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_tax(company_id,
  code),
  FOREIGN KEY(company_id) REFERENCES companies(id),
  FOREIGN KEY(input_tax_account_id) REFERENCES accounts(id),
  FOREIGN KEY(output_tax_account_id) REFERENCES accounts(id)) ENGINE=InnoDB;
CREATE TABLE cost_centers(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  code VARCHAR(30) NOT NULL,
  name VARCHAR(150) NOT NULL,
  description TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE KEY uq_cost_center(company_id,
  code),
  FOREIGN KEY(company_id) REFERENCES companies(id)) ENGINE=InnoDB;
CREATE TABLE projects(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  code VARCHAR(30) NOT NULL,
  name VARCHAR(191) NOT NULL,
  customer_id BIGINT UNSIGNED,
  start_date DATE,
  end_date DATE,
  status VARCHAR(30),
  budget DECIMAL(20,
  2) NOT NULL DEFAULT 0,
  description TEXT,
  UNIQUE KEY uq_project(company_id,
  code),
  FOREIGN KEY(company_id) REFERENCES companies(id),
  FOREIGN KEY(customer_id) REFERENCES customers(id)) ENGINE=InnoDB;
CREATE TABLE items(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  sku VARCHAR(50) NOT NULL,
  barcode VARCHAR(100),
  name VARCHAR(191) NOT NULL,
  description TEXT,
  item_type ENUM('inventory',
  'service',
  'non_inventory') NOT NULL,
  unit_id BIGINT UNSIGNED NOT NULL,
  sales_account_id BIGINT UNSIGNED,
  inventory_account_id BIGINT UNSIGNED,
  cogs_account_id BIGINT UNSIGNED,
  purchase_account_id BIGINT UNSIGNED,
  sales_price DECIMAL(20,
  2) NOT NULL DEFAULT 0,
  purchase_price DECIMAL(20,
  2) NOT NULL DEFAULT 0,
  average_cost DECIMAL(20,
  2) NOT NULL DEFAULT 0,
  minimum_stock DECIMAL(20,
  4) NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  UNIQUE KEY uq_item(company_id,
  sku),
  FOREIGN KEY(company_id) REFERENCES companies(id),
  FOREIGN KEY(unit_id) REFERENCES units(id),
  FOREIGN KEY(sales_account_id) REFERENCES accounts(id),
  FOREIGN KEY(inventory_account_id) REFERENCES accounts(id),
  FOREIGN KEY(cogs_account_id) REFERENCES accounts(id),
  FOREIGN KEY(purchase_account_id) REFERENCES accounts(id)) ENGINE=InnoDB;`),
  down: async (db: { query: (sql: string) => Promise<unknown> }) => {
    for (const t of [
      'items',
      'projects',
      'cost_centers',
      'tax_codes',
      'warehouses',
      'units',
      'suppliers',
      'customers',
    ])
      await db.query(`DROP TABLE IF EXISTS ${t}`)
  },
}
