export const migration = {
  name: '003_accounting_transactions',
  up: async (db: { query: (sql: string) => Promise<unknown> }) =>
    db.query(`
CREATE TABLE journals(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  journal_number VARCHAR(50) NOT NULL,
  journal_date DATE NOT NULL,
  reference VARCHAR(100),
  description TEXT,
  source_type VARCHAR(50),
  source_id BIGINT UNSIGNED,
  status ENUM('draft',
  'pending_approval',
  'approved',
  'posted',
  'reversed',
  'cancelled') NOT NULL DEFAULT 'draft',
  created_by BIGINT UNSIGNED NOT NULL,
  approved_by BIGINT UNSIGNED,
  posted_by BIGINT UNSIGNED,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  approved_at DATETIME,
  posted_at DATETIME,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_journal(company_id,
  journal_number),
  FOREIGN KEY(company_id) REFERENCES companies(id),
  FOREIGN KEY(created_by) REFERENCES users(id),
  FOREIGN KEY(approved_by) REFERENCES users(id),
  FOREIGN KEY(posted_by) REFERENCES users(id),
  INDEX idx_journal(company_id,
  journal_date,
  status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE journal_lines(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  journal_id BIGINT UNSIGNED NOT NULL,
  account_id BIGINT UNSIGNED NOT NULL,
  description VARCHAR(255),
  cost_center_id BIGINT UNSIGNED,
  project_id BIGINT UNSIGNED,
  debit DECIMAL(20,
  2) NOT NULL DEFAULT 0,
  credit DECIMAL(20,
  2) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(journal_id) REFERENCES journals(id) ON DELETE CASCADE,
  FOREIGN KEY(account_id) REFERENCES accounts(id),
  FOREIGN KEY(cost_center_id) REFERENCES cost_centers(id),
  FOREIGN KEY(project_id) REFERENCES projects(id),
  CHECK(debit>=0 AND credit>=0),
  CHECK(NOT(debit>0 AND credit>0)),
  INDEX idx_journal_line_account(account_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE inventory_balances(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  item_id BIGINT UNSIGNED NOT NULL,
  warehouse_id BIGINT UNSIGNED NOT NULL,
  quantity DECIMAL(20,
  4) NOT NULL DEFAULT 0,
  average_cost DECIMAL(20,
  2) NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_inventory_balance(company_id,
  item_id,
  warehouse_id),
  FOREIGN KEY(company_id) REFERENCES companies(id),
  FOREIGN KEY(item_id) REFERENCES items(id),
  FOREIGN KEY(warehouse_id) REFERENCES warehouses(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE inventory_movements(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  item_id BIGINT UNSIGNED NOT NULL,
  warehouse_id BIGINT UNSIGNED NOT NULL,
  transaction_type VARCHAR(50) NOT NULL,
  transaction_id BIGINT UNSIGNED NOT NULL,
  transaction_number VARCHAR(50) NOT NULL,
  movement_date DATE NOT NULL,
  quantity_in DECIMAL(20,
  4) NOT NULL DEFAULT 0,
  quantity_out DECIMAL(20,
  4) NOT NULL DEFAULT 0,
  unit_cost DECIMAL(20,
  2) NOT NULL,
  total_cost DECIMAL(20,
  2) NOT NULL,
  running_quantity DECIMAL(20,
  4) NOT NULL,
  running_value DECIMAL(20,
  2) NOT NULL,
  reference VARCHAR(100),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NOT NULL,
  FOREIGN KEY(company_id) REFERENCES companies(id),
  FOREIGN KEY(item_id) REFERENCES items(id),
  FOREIGN KEY(warehouse_id) REFERENCES warehouses(id),
  FOREIGN KEY(created_by) REFERENCES users(id),
  INDEX idx_inventory_card(company_id,
  item_id,
  warehouse_id,
  movement_date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE sales_invoices(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  invoice_number VARCHAR(50) NOT NULL,
  invoice_date DATE NOT NULL,
  due_date DATE NOT NULL,
  customer_id BIGINT UNSIGNED NOT NULL,
  warehouse_id BIGINT UNSIGNED,
  reference VARCHAR(100),
  subtotal DECIMAL(20,
  2) NOT NULL,
  discount DECIMAL(20,
  2) NOT NULL DEFAULT 0,
  tax DECIMAL(20,
  2) NOT NULL DEFAULT 0,
  grand_total DECIMAL(20,
  2) NOT NULL,
  paid_amount DECIMAL(20,
  2) NOT NULL DEFAULT 0,
  outstanding_amount DECIMAL(20,
  2) NOT NULL,
  status ENUM('draft',
  'pending_approval',
  'approved',
  'posted',
  'partially_paid',
  'paid',
  'cancelled') NOT NULL DEFAULT 'draft',
  approval_status VARCHAR(30),
  created_by BIGINT UNSIGNED NOT NULL,
  approved_by BIGINT UNSIGNED,
  posted_by BIGINT UNSIGNED,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  posted_at DATETIME,
  UNIQUE KEY uq_sales_invoice(company_id,
  invoice_number),
  FOREIGN KEY(company_id) REFERENCES companies(id),
  FOREIGN KEY(customer_id) REFERENCES customers(id),
  FOREIGN KEY(warehouse_id) REFERENCES warehouses(id),
  FOREIGN KEY(created_by) REFERENCES users(id),
  INDEX idx_sales_invoice(company_id,
  invoice_date,
  status,
  customer_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE sales_invoice_lines(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  sales_invoice_id BIGINT UNSIGNED NOT NULL,
  item_id BIGINT UNSIGNED NOT NULL,
  description VARCHAR(255),
  quantity DECIMAL(20,
  4) NOT NULL,
  unit_id BIGINT UNSIGNED NOT NULL,
  unit_price DECIMAL(20,
  2) NOT NULL,
  discount DECIMAL(20,
  2) NOT NULL DEFAULT 0,
  tax_code_id BIGINT UNSIGNED,
  tax_amount DECIMAL(20,
  2) NOT NULL DEFAULT 0,
  subtotal DECIMAL(20,
  2) NOT NULL,
  cogs_amount DECIMAL(20,
  2) NOT NULL DEFAULT 0,
  FOREIGN KEY(sales_invoice_id) REFERENCES sales_invoices(id),
  FOREIGN KEY(item_id) REFERENCES items(id),
  FOREIGN KEY(unit_id) REFERENCES units(id),
  FOREIGN KEY(tax_code_id) REFERENCES tax_codes(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE purchase_invoices(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  invoice_number VARCHAR(50) NOT NULL,
  supplier_invoice_number VARCHAR(100),
  invoice_date DATE NOT NULL,
  due_date DATE NOT NULL,
  supplier_id BIGINT UNSIGNED NOT NULL,
  warehouse_id BIGINT UNSIGNED,
  subtotal DECIMAL(20,
  2) NOT NULL,
  discount DECIMAL(20,
  2) NOT NULL DEFAULT 0,
  tax DECIMAL(20,
  2) NOT NULL DEFAULT 0,
  grand_total DECIMAL(20,
  2) NOT NULL,
  paid_amount DECIMAL(20,
  2) NOT NULL DEFAULT 0,
  outstanding_amount DECIMAL(20,
  2) NOT NULL,
  status ENUM('draft',
  'pending_approval',
  'approved',
  'posted',
  'partially_paid',
  'paid',
  'cancelled') NOT NULL DEFAULT 'draft',
  created_by BIGINT UNSIGNED NOT NULL,
  posted_by BIGINT UNSIGNED,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  posted_at DATETIME,
  UNIQUE KEY uq_purchase_invoice(company_id,
  invoice_number),
  FOREIGN KEY(company_id) REFERENCES companies(id),
  FOREIGN KEY(supplier_id) REFERENCES suppliers(id),
  FOREIGN KEY(warehouse_id) REFERENCES warehouses(id),
  FOREIGN KEY(created_by) REFERENCES users(id),
  INDEX idx_purchase_invoice(company_id,
  invoice_date,
  status,
  supplier_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE purchase_invoice_lines(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  purchase_invoice_id BIGINT UNSIGNED NOT NULL,
  item_id BIGINT UNSIGNED NOT NULL,
  description VARCHAR(255),
  quantity DECIMAL(20,
  4) NOT NULL,
  unit_id BIGINT UNSIGNED NOT NULL,
  unit_price DECIMAL(20,
  2) NOT NULL,
  discount DECIMAL(20,
  2) NOT NULL DEFAULT 0,
  tax_code_id BIGINT UNSIGNED,
  tax_amount DECIMAL(20,
  2) NOT NULL DEFAULT 0,
  subtotal DECIMAL(20,
  2) NOT NULL,
  FOREIGN KEY(purchase_invoice_id) REFERENCES purchase_invoices(id),
  FOREIGN KEY(item_id) REFERENCES items(id),
  FOREIGN KEY(unit_id) REFERENCES units(id),
  FOREIGN KEY(tax_code_id) REFERENCES tax_codes(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`),
  down: async (db: { query: (sql: string) => Promise<unknown> }) => {
    for (const t of [
      'purchase_invoice_lines',
      'purchase_invoices',
      'sales_invoice_lines',
      'sales_invoices',
      'inventory_movements',
      'inventory_balances',
      'journal_lines',
      'journals',
    ])
      await db.query(`DROP TABLE IF EXISTS ${t}`)
  },
}
