import {
  addColumnIfMissing,
  addForeignKeyIfMissing,
  addIndexIfMissing,
  dropColumnIfExists,
  dropForeignKeyIfExists,
  dropIndexIfExists,
  dropTables,
  type MigrationDatabase,
} from './helpers'

async function createSalesOrderTables(db: MigrationDatabase) {
  await db.query(`CREATE TABLE IF NOT EXISTS sales_orders(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    order_number VARCHAR(50) NOT NULL,
    order_date DATE NOT NULL,
    customer_id BIGINT UNSIGNED NOT NULL,
    warehouse_id BIGINT UNSIGNED NOT NULL,
    sales_person_id BIGINT UNSIGNED NULL,
    payment_term_days INT UNSIGNED NOT NULL DEFAULT 0,
    expected_date DATE NULL,
    reference VARCHAR(100),
    currency CHAR(3) NOT NULL DEFAULT 'IDR',
    exchange_rate DECIMAL(20,8) NOT NULL DEFAULT 1,
    subtotal DECIMAL(20,2) NOT NULL DEFAULT 0,
    discount DECIMAL(20,2) NOT NULL DEFAULT 0,
    tax DECIMAL(20,2) NOT NULL DEFAULT 0,
    grand_total DECIMAL(20,2) NOT NULL DEFAULT 0,
    base_grand_total DECIMAL(20,2) NOT NULL DEFAULT 0,
    notes TEXT,
    status ENUM('draft','confirmed','partially_invoiced','invoiced','cancelled') NOT NULL DEFAULT 'draft',
    fulfillment_status ENUM('not_delivered','partial','delivered') NOT NULL DEFAULT 'not_delivered',
    created_by BIGINT UNSIGNED NOT NULL,
    updated_by BIGINT UNSIGNED NULL,
    confirmed_by BIGINT UNSIGNED NULL,
    confirmed_at DATETIME NULL,
    cancelled_by BIGINT UNSIGNED NULL,
    cancelled_at DATETIME NULL,
    cancellation_reason TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    UNIQUE KEY uq_sales_order(company_id, order_number),
    CONSTRAINT fk_sales_order_company FOREIGN KEY(company_id) REFERENCES companies(id),
    CONSTRAINT fk_sales_order_customer FOREIGN KEY(customer_id) REFERENCES customers(id),
    CONSTRAINT fk_sales_order_warehouse FOREIGN KEY(warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_sales_order_sales_person FOREIGN KEY(sales_person_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_sales_order_created_by FOREIGN KEY(created_by) REFERENCES users(id),
    CONSTRAINT fk_sales_order_updated_by FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_sales_order_confirmed_by FOREIGN KEY(confirmed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_sales_order_cancelled_by FOREIGN KEY(cancelled_by) REFERENCES users(id) ON DELETE SET NULL,
    CHECK(exchange_rate > 0),
    CHECK(grand_total >= 0),
    INDEX idx_sales_order_list(company_id, order_date, status, customer_id),
    INDEX idx_sales_order_expected(company_id, expected_date, fulfillment_status)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS sales_order_lines(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sales_order_id BIGINT UNSIGNED NOT NULL,
    line_number INT UNSIGNED NOT NULL,
    item_id BIGINT UNSIGNED NOT NULL,
    description VARCHAR(255),
    quantity DECIMAL(20,4) NOT NULL,
    delivered_quantity DECIMAL(20,4) NOT NULL DEFAULT 0,
    invoiced_quantity DECIMAL(20,4) NOT NULL DEFAULT 0,
    unit_id BIGINT UNSIGNED NOT NULL,
    unit_price DECIMAL(20,4) NOT NULL,
    discount_percent DECIMAL(9,6) NOT NULL DEFAULT 0,
    discount_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    tax_code_id BIGINT UNSIGNED NULL,
    tax_rate DECIMAL(8,4) NOT NULL DEFAULT 0,
    tax_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    subtotal DECIMAL(20,2) NOT NULL,
    base_subtotal DECIMAL(20,2) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_sales_order_line(sales_order_id, line_number),
    CONSTRAINT fk_sales_order_line_order FOREIGN KEY(sales_order_id) REFERENCES sales_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_sales_order_line_item FOREIGN KEY(item_id) REFERENCES items(id),
    CONSTRAINT fk_sales_order_line_unit FOREIGN KEY(unit_id) REFERENCES units(id),
    CONSTRAINT fk_sales_order_line_tax FOREIGN KEY(tax_code_id) REFERENCES tax_codes(id),
    CHECK(quantity > 0),
    CHECK(delivered_quantity >= 0 AND delivered_quantity <= quantity),
    CHECK(invoiced_quantity >= 0 AND invoiced_quantity <= quantity),
    CHECK(discount_percent >= 0 AND discount_percent <= 100),
    INDEX idx_sales_order_line_item(item_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)
}

async function createDeliveryTables(db: MigrationDatabase) {
  await db.query(`CREATE TABLE IF NOT EXISTS delivery_orders(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    delivery_number VARCHAR(50) NOT NULL,
    delivery_date DATE NOT NULL,
    sales_order_id BIGINT UNSIGNED NOT NULL,
    customer_id BIGINT UNSIGNED NOT NULL,
    warehouse_id BIGINT UNSIGNED NOT NULL,
    reference VARCHAR(100),
    notes TEXT,
    status ENUM('draft','confirmed','posted','reversed','cancelled') NOT NULL DEFAULT 'draft',
    journal_id BIGINT UNSIGNED NULL,
    reversal_journal_id BIGINT UNSIGNED NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    updated_by BIGINT UNSIGNED NULL,
    confirmed_by BIGINT UNSIGNED NULL,
    confirmed_at DATETIME NULL,
    posted_by BIGINT UNSIGNED NULL,
    posted_at DATETIME NULL,
    reversed_by BIGINT UNSIGNED NULL,
    reversed_at DATETIME NULL,
    cancelled_by BIGINT UNSIGNED NULL,
    cancelled_at DATETIME NULL,
    cancellation_reason TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    UNIQUE KEY uq_delivery_order(company_id, delivery_number),
    CONSTRAINT fk_delivery_company FOREIGN KEY(company_id) REFERENCES companies(id),
    CONSTRAINT fk_delivery_sales_order FOREIGN KEY(sales_order_id) REFERENCES sales_orders(id),
    CONSTRAINT fk_delivery_customer FOREIGN KEY(customer_id) REFERENCES customers(id),
    CONSTRAINT fk_delivery_warehouse FOREIGN KEY(warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_delivery_journal FOREIGN KEY(journal_id) REFERENCES journals(id) ON DELETE SET NULL,
    CONSTRAINT fk_delivery_reversal_journal FOREIGN KEY(reversal_journal_id) REFERENCES journals(id) ON DELETE SET NULL,
    CONSTRAINT fk_delivery_created_by FOREIGN KEY(created_by) REFERENCES users(id),
    CONSTRAINT fk_delivery_updated_by FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_delivery_confirmed_by FOREIGN KEY(confirmed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_delivery_posted_by FOREIGN KEY(posted_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_delivery_reversed_by FOREIGN KEY(reversed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_delivery_cancelled_by FOREIGN KEY(cancelled_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_delivery_list(company_id, delivery_date, status, customer_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS delivery_order_lines(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    delivery_order_id BIGINT UNSIGNED NOT NULL,
    sales_order_line_id BIGINT UNSIGNED NOT NULL,
    line_number INT UNSIGNED NOT NULL,
    item_id BIGINT UNSIGNED NOT NULL,
    description VARCHAR(255),
    quantity DECIMAL(20,4) NOT NULL,
    unit_id BIGINT UNSIGNED NOT NULL,
    unit_cost DECIMAL(20,6) NOT NULL DEFAULT 0,
    inventory_movement_id BIGINT UNSIGNED NULL,
    UNIQUE KEY uq_delivery_order_line(delivery_order_id, line_number),
    CONSTRAINT fk_delivery_line_delivery FOREIGN KEY(delivery_order_id) REFERENCES delivery_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_delivery_line_sales_order FOREIGN KEY(sales_order_line_id) REFERENCES sales_order_lines(id),
    CONSTRAINT fk_delivery_line_item FOREIGN KEY(item_id) REFERENCES items(id),
    CONSTRAINT fk_delivery_line_unit FOREIGN KEY(unit_id) REFERENCES units(id),
    CONSTRAINT fk_delivery_line_movement FOREIGN KEY(inventory_movement_id) REFERENCES inventory_movements(id) ON DELETE SET NULL,
    CHECK(quantity > 0),
    INDEX idx_delivery_line_item(item_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)
}

async function createPurchaseOrderTables(db: MigrationDatabase) {
  await db.query(`CREATE TABLE IF NOT EXISTS purchase_orders(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    order_number VARCHAR(50) NOT NULL,
    order_date DATE NOT NULL,
    supplier_id BIGINT UNSIGNED NOT NULL,
    warehouse_id BIGINT UNSIGNED NOT NULL,
    buyer_id BIGINT UNSIGNED NULL,
    payment_term_days INT UNSIGNED NOT NULL DEFAULT 0,
    expected_date DATE NULL,
    supplier_reference VARCHAR(100),
    currency CHAR(3) NOT NULL DEFAULT 'IDR',
    exchange_rate DECIMAL(20,8) NOT NULL DEFAULT 1,
    subtotal DECIMAL(20,2) NOT NULL DEFAULT 0,
    discount DECIMAL(20,2) NOT NULL DEFAULT 0,
    tax DECIMAL(20,2) NOT NULL DEFAULT 0,
    grand_total DECIMAL(20,2) NOT NULL DEFAULT 0,
    base_grand_total DECIMAL(20,2) NOT NULL DEFAULT 0,
    notes TEXT,
    status ENUM('draft','confirmed','partially_received','partially_billed','completed','cancelled') NOT NULL DEFAULT 'draft',
    receipt_status ENUM('not_received','partial','received') NOT NULL DEFAULT 'not_received',
    billing_status ENUM('not_billed','partial','billed') NOT NULL DEFAULT 'not_billed',
    created_by BIGINT UNSIGNED NOT NULL,
    updated_by BIGINT UNSIGNED NULL,
    confirmed_by BIGINT UNSIGNED NULL,
    confirmed_at DATETIME NULL,
    cancelled_by BIGINT UNSIGNED NULL,
    cancelled_at DATETIME NULL,
    cancellation_reason TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    UNIQUE KEY uq_purchase_order(company_id, order_number),
    CONSTRAINT fk_purchase_order_company FOREIGN KEY(company_id) REFERENCES companies(id),
    CONSTRAINT fk_purchase_order_supplier FOREIGN KEY(supplier_id) REFERENCES suppliers(id),
    CONSTRAINT fk_purchase_order_warehouse FOREIGN KEY(warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_purchase_order_buyer FOREIGN KEY(buyer_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_purchase_order_created_by FOREIGN KEY(created_by) REFERENCES users(id),
    CONSTRAINT fk_purchase_order_updated_by FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_purchase_order_confirmed_by FOREIGN KEY(confirmed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_purchase_order_cancelled_by FOREIGN KEY(cancelled_by) REFERENCES users(id) ON DELETE SET NULL,
    CHECK(exchange_rate > 0),
    CHECK(grand_total >= 0),
    INDEX idx_purchase_order_list(company_id, order_date, status, supplier_id),
    INDEX idx_purchase_order_expected(company_id, expected_date, receipt_status)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS purchase_order_lines(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    purchase_order_id BIGINT UNSIGNED NOT NULL,
    line_number INT UNSIGNED NOT NULL,
    item_id BIGINT UNSIGNED NOT NULL,
    description VARCHAR(255),
    quantity DECIMAL(20,4) NOT NULL,
    received_quantity DECIMAL(20,4) NOT NULL DEFAULT 0,
    billed_quantity DECIMAL(20,4) NOT NULL DEFAULT 0,
    unit_id BIGINT UNSIGNED NOT NULL,
    unit_price DECIMAL(20,4) NOT NULL,
    discount_percent DECIMAL(9,6) NOT NULL DEFAULT 0,
    discount_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    tax_code_id BIGINT UNSIGNED NULL,
    tax_rate DECIMAL(8,4) NOT NULL DEFAULT 0,
    tax_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    subtotal DECIMAL(20,2) NOT NULL,
    base_subtotal DECIMAL(20,2) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_purchase_order_line(purchase_order_id, line_number),
    CONSTRAINT fk_purchase_order_line_order FOREIGN KEY(purchase_order_id) REFERENCES purchase_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_purchase_order_line_item FOREIGN KEY(item_id) REFERENCES items(id),
    CONSTRAINT fk_purchase_order_line_unit FOREIGN KEY(unit_id) REFERENCES units(id),
    CONSTRAINT fk_purchase_order_line_tax FOREIGN KEY(tax_code_id) REFERENCES tax_codes(id),
    CHECK(quantity > 0),
    CHECK(received_quantity >= 0 AND received_quantity <= quantity),
    CHECK(billed_quantity >= 0 AND billed_quantity <= quantity),
    CHECK(discount_percent >= 0 AND discount_percent <= 100),
    INDEX idx_purchase_order_line_item(item_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)
}

async function createGoodsReceiptTables(db: MigrationDatabase) {
  await db.query(`CREATE TABLE IF NOT EXISTS goods_receipts(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    receipt_number VARCHAR(50) NOT NULL,
    receipt_date DATE NOT NULL,
    purchase_order_id BIGINT UNSIGNED NOT NULL,
    supplier_id BIGINT UNSIGNED NOT NULL,
    warehouse_id BIGINT UNSIGNED NOT NULL,
    supplier_delivery_number VARCHAR(100),
    reference VARCHAR(100),
    notes TEXT,
    status ENUM('draft','posted','reversed','cancelled') NOT NULL DEFAULT 'draft',
    journal_id BIGINT UNSIGNED NULL,
    reversal_journal_id BIGINT UNSIGNED NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    updated_by BIGINT UNSIGNED NULL,
    posted_by BIGINT UNSIGNED NULL,
    posted_at DATETIME NULL,
    reversed_by BIGINT UNSIGNED NULL,
    reversed_at DATETIME NULL,
    cancelled_by BIGINT UNSIGNED NULL,
    cancelled_at DATETIME NULL,
    cancellation_reason TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    UNIQUE KEY uq_goods_receipt(company_id, receipt_number),
    CONSTRAINT fk_goods_receipt_company FOREIGN KEY(company_id) REFERENCES companies(id),
    CONSTRAINT fk_goods_receipt_purchase_order FOREIGN KEY(purchase_order_id) REFERENCES purchase_orders(id),
    CONSTRAINT fk_goods_receipt_supplier FOREIGN KEY(supplier_id) REFERENCES suppliers(id),
    CONSTRAINT fk_goods_receipt_warehouse FOREIGN KEY(warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_goods_receipt_journal FOREIGN KEY(journal_id) REFERENCES journals(id) ON DELETE SET NULL,
    CONSTRAINT fk_goods_receipt_reversal_journal FOREIGN KEY(reversal_journal_id) REFERENCES journals(id) ON DELETE SET NULL,
    CONSTRAINT fk_goods_receipt_created_by FOREIGN KEY(created_by) REFERENCES users(id),
    CONSTRAINT fk_goods_receipt_updated_by FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_goods_receipt_posted_by FOREIGN KEY(posted_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_goods_receipt_reversed_by FOREIGN KEY(reversed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_goods_receipt_cancelled_by FOREIGN KEY(cancelled_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_goods_receipt_list(company_id, receipt_date, status, supplier_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS goods_receipt_lines(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    goods_receipt_id BIGINT UNSIGNED NOT NULL,
    purchase_order_line_id BIGINT UNSIGNED NOT NULL,
    line_number INT UNSIGNED NOT NULL,
    item_id BIGINT UNSIGNED NOT NULL,
    description VARCHAR(255),
    quantity DECIMAL(20,4) NOT NULL,
    billed_quantity DECIMAL(20,4) NOT NULL DEFAULT 0,
    unit_id BIGINT UNSIGNED NOT NULL,
    unit_cost DECIMAL(20,6) NOT NULL,
    inventory_movement_id BIGINT UNSIGNED NULL,
    UNIQUE KEY uq_goods_receipt_line(goods_receipt_id, line_number),
    CONSTRAINT fk_goods_receipt_line_receipt FOREIGN KEY(goods_receipt_id) REFERENCES goods_receipts(id) ON DELETE CASCADE,
    CONSTRAINT fk_goods_receipt_line_po_line FOREIGN KEY(purchase_order_line_id) REFERENCES purchase_order_lines(id),
    CONSTRAINT fk_goods_receipt_line_item FOREIGN KEY(item_id) REFERENCES items(id),
    CONSTRAINT fk_goods_receipt_line_unit FOREIGN KEY(unit_id) REFERENCES units(id),
    CONSTRAINT fk_goods_receipt_line_movement FOREIGN KEY(inventory_movement_id) REFERENCES inventory_movements(id) ON DELETE SET NULL,
    CHECK(quantity > 0),
    CHECK(billed_quantity >= 0 AND billed_quantity <= quantity),
    INDEX idx_goods_receipt_line_item(item_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)
}

async function linkExistingInvoices(db: MigrationDatabase) {
  await addColumnIfMissing(db, 'sales_invoices', 'sales_order_id', 'BIGINT UNSIGNED NULL')
  await addColumnIfMissing(db, 'sales_invoices', 'delivery_order_id', 'BIGINT UNSIGNED NULL')
  await addForeignKeyIfMissing(
    db,
    'sales_invoices',
    'fk_sales_invoice_sales_order',
    'FOREIGN KEY (sales_order_id) REFERENCES sales_orders(id)',
  )
  await addForeignKeyIfMissing(
    db,
    'sales_invoices',
    'fk_sales_invoice_delivery',
    'FOREIGN KEY (delivery_order_id) REFERENCES delivery_orders(id)',
  )
  await addIndexIfMissing(
    db,
    'sales_invoices',
    'idx_sales_invoice_order',
    'INDEX idx_sales_invoice_order(company_id, sales_order_id)',
  )

  await addColumnIfMissing(db, 'sales_invoice_lines', 'sales_order_line_id', 'BIGINT UNSIGNED NULL')
  await addColumnIfMissing(
    db,
    'sales_invoice_lines',
    'delivery_order_line_id',
    'BIGINT UNSIGNED NULL',
  )
  await addForeignKeyIfMissing(
    db,
    'sales_invoice_lines',
    'fk_sales_invoice_line_order_line',
    'FOREIGN KEY (sales_order_line_id) REFERENCES sales_order_lines(id)',
  )
  await addForeignKeyIfMissing(
    db,
    'sales_invoice_lines',
    'fk_sales_invoice_line_delivery_line',
    'FOREIGN KEY (delivery_order_line_id) REFERENCES delivery_order_lines(id)',
  )

  await addColumnIfMissing(db, 'purchase_invoices', 'purchase_order_id', 'BIGINT UNSIGNED NULL')
  await addColumnIfMissing(db, 'purchase_invoices', 'goods_receipt_id', 'BIGINT UNSIGNED NULL')
  await addForeignKeyIfMissing(
    db,
    'purchase_invoices',
    'fk_purchase_invoice_purchase_order',
    'FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id)',
  )
  await addForeignKeyIfMissing(
    db,
    'purchase_invoices',
    'fk_purchase_invoice_goods_receipt',
    'FOREIGN KEY (goods_receipt_id) REFERENCES goods_receipts(id)',
  )
  await addIndexIfMissing(
    db,
    'purchase_invoices',
    'idx_purchase_invoice_order',
    'INDEX idx_purchase_invoice_order(company_id, purchase_order_id)',
  )

  await addColumnIfMissing(
    db,
    'purchase_invoice_lines',
    'purchase_order_line_id',
    'BIGINT UNSIGNED NULL',
  )
  await addColumnIfMissing(
    db,
    'purchase_invoice_lines',
    'goods_receipt_line_id',
    'BIGINT UNSIGNED NULL',
  )
  await addForeignKeyIfMissing(
    db,
    'purchase_invoice_lines',
    'fk_purchase_invoice_line_order_line',
    'FOREIGN KEY (purchase_order_line_id) REFERENCES purchase_order_lines(id)',
  )
  await addForeignKeyIfMissing(
    db,
    'purchase_invoice_lines',
    'fk_purchase_invoice_line_receipt_line',
    'FOREIGN KEY (goods_receipt_line_id) REFERENCES goods_receipt_lines(id)',
  )

  await db.query(`CREATE TABLE IF NOT EXISTS sales_invoice_deliveries(
    sales_invoice_id BIGINT UNSIGNED NOT NULL,
    delivery_order_id BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY(sales_invoice_id, delivery_order_id),
    CONSTRAINT fk_invoice_delivery_invoice FOREIGN KEY(sales_invoice_id) REFERENCES sales_invoices(id) ON DELETE CASCADE,
    CONSTRAINT fk_invoice_delivery_delivery FOREIGN KEY(delivery_order_id) REFERENCES delivery_orders(id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS purchase_invoice_receipts(
    purchase_invoice_id BIGINT UNSIGNED NOT NULL,
    goods_receipt_id BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY(purchase_invoice_id, goods_receipt_id),
    CONSTRAINT fk_invoice_receipt_invoice FOREIGN KEY(purchase_invoice_id) REFERENCES purchase_invoices(id) ON DELETE CASCADE,
    CONSTRAINT fk_invoice_receipt_receipt FOREIGN KEY(goods_receipt_id) REFERENCES goods_receipts(id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)
}

async function createSalesReturnTables(db: MigrationDatabase) {
  await db.query(`CREATE TABLE IF NOT EXISTS sales_returns(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    return_number VARCHAR(50) NOT NULL,
    return_date DATE NOT NULL,
    sales_invoice_id BIGINT UNSIGNED NOT NULL,
    customer_id BIGINT UNSIGNED NOT NULL,
    warehouse_id BIGINT UNSIGNED NULL,
    reference VARCHAR(100),
    currency CHAR(3) NOT NULL DEFAULT 'IDR',
    exchange_rate DECIMAL(20,8) NOT NULL DEFAULT 1,
    subtotal DECIMAL(20,2) NOT NULL DEFAULT 0,
    discount DECIMAL(20,2) NOT NULL DEFAULT 0,
    tax DECIMAL(20,2) NOT NULL DEFAULT 0,
    grand_total DECIMAL(20,2) NOT NULL DEFAULT 0,
    base_grand_total DECIMAL(20,2) NOT NULL DEFAULT 0,
    reason TEXT NOT NULL,
    status ENUM('draft','pending_approval','approved','posted','rejected','reversed','cancelled') NOT NULL DEFAULT 'draft',
    journal_id BIGINT UNSIGNED NULL,
    reversal_journal_id BIGINT UNSIGNED NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    updated_by BIGINT UNSIGNED NULL,
    submitted_by BIGINT UNSIGNED NULL,
    submitted_at DATETIME NULL,
    approved_by BIGINT UNSIGNED NULL,
    approved_at DATETIME NULL,
    rejected_by BIGINT UNSIGNED NULL,
    rejected_at DATETIME NULL,
    rejection_reason TEXT NULL,
    posted_by BIGINT UNSIGNED NULL,
    posted_at DATETIME NULL,
    reversed_by BIGINT UNSIGNED NULL,
    reversed_at DATETIME NULL,
    cancelled_by BIGINT UNSIGNED NULL,
    cancelled_at DATETIME NULL,
    cancellation_reason TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    UNIQUE KEY uq_sales_return(company_id, return_number),
    CONSTRAINT fk_sales_return_company FOREIGN KEY(company_id) REFERENCES companies(id),
    CONSTRAINT fk_sales_return_invoice FOREIGN KEY(sales_invoice_id) REFERENCES sales_invoices(id),
    CONSTRAINT fk_sales_return_customer FOREIGN KEY(customer_id) REFERENCES customers(id),
    CONSTRAINT fk_sales_return_warehouse FOREIGN KEY(warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_sales_return_journal FOREIGN KEY(journal_id) REFERENCES journals(id) ON DELETE SET NULL,
    CONSTRAINT fk_sales_return_reversal_journal FOREIGN KEY(reversal_journal_id) REFERENCES journals(id) ON DELETE SET NULL,
    CONSTRAINT fk_sales_return_created_by FOREIGN KEY(created_by) REFERENCES users(id),
    CONSTRAINT fk_sales_return_updated_by FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_sales_return_submitted_by FOREIGN KEY(submitted_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_sales_return_approved_by FOREIGN KEY(approved_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_sales_return_rejected_by FOREIGN KEY(rejected_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_sales_return_posted_by FOREIGN KEY(posted_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_sales_return_reversed_by FOREIGN KEY(reversed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_sales_return_cancelled_by FOREIGN KEY(cancelled_by) REFERENCES users(id) ON DELETE SET NULL,
    CHECK(exchange_rate > 0),
    CHECK(grand_total >= 0),
    INDEX idx_sales_return_list(company_id, return_date, status, customer_id),
    INDEX idx_sales_return_invoice(company_id, sales_invoice_id, status)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS sales_return_lines(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sales_return_id BIGINT UNSIGNED NOT NULL,
    sales_invoice_line_id BIGINT UNSIGNED NOT NULL,
    line_number INT UNSIGNED NOT NULL,
    item_id BIGINT UNSIGNED NOT NULL,
    description VARCHAR(255),
    quantity DECIMAL(20,4) NOT NULL,
    unit_id BIGINT UNSIGNED NOT NULL,
    unit_price DECIMAL(20,4) NOT NULL,
    discount DECIMAL(20,2) NOT NULL DEFAULT 0,
    tax_code_id BIGINT UNSIGNED NULL,
    tax_rate DECIMAL(8,4) NOT NULL DEFAULT 0,
    tax_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    subtotal DECIMAL(20,2) NOT NULL,
    base_subtotal DECIMAL(20,2) NOT NULL,
    cogs_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    reason VARCHAR(255),
    inventory_movement_id BIGINT UNSIGNED NULL,
    UNIQUE KEY uq_sales_return_line(sales_return_id, line_number),
    CONSTRAINT fk_sales_return_line_return FOREIGN KEY(sales_return_id) REFERENCES sales_returns(id) ON DELETE CASCADE,
    CONSTRAINT fk_sales_return_line_invoice_line FOREIGN KEY(sales_invoice_line_id) REFERENCES sales_invoice_lines(id),
    CONSTRAINT fk_sales_return_line_item FOREIGN KEY(item_id) REFERENCES items(id),
    CONSTRAINT fk_sales_return_line_unit FOREIGN KEY(unit_id) REFERENCES units(id),
    CONSTRAINT fk_sales_return_line_tax FOREIGN KEY(tax_code_id) REFERENCES tax_codes(id),
    CONSTRAINT fk_sales_return_line_movement FOREIGN KEY(inventory_movement_id) REFERENCES inventory_movements(id) ON DELETE SET NULL,
    CHECK(quantity > 0),
    INDEX idx_sales_return_line_invoice(sales_invoice_line_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)
}

async function createCustomerPaymentTables(db: MigrationDatabase) {
  await db.query(`CREATE TABLE IF NOT EXISTS customer_payments(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    payment_number VARCHAR(50) NOT NULL,
    payment_date DATE NOT NULL,
    customer_id BIGINT UNSIGNED NOT NULL,
    bank_account_id BIGINT UNSIGNED NULL,
    cash_account_id BIGINT UNSIGNED NOT NULL,
    payment_method ENUM('cash','bank_transfer','check','card','other') NOT NULL,
    reference VARCHAR(100),
    currency CHAR(3) NOT NULL DEFAULT 'IDR',
    exchange_rate DECIMAL(20,8) NOT NULL DEFAULT 1,
    amount DECIMAL(20,2) NOT NULL,
    base_amount DECIMAL(20,2) NOT NULL,
    unallocated_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    notes TEXT,
    status ENUM('draft','pending_approval','approved','posted','rejected','reversed','cancelled') NOT NULL DEFAULT 'draft',
    journal_id BIGINT UNSIGNED NULL,
    reversal_journal_id BIGINT UNSIGNED NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    updated_by BIGINT UNSIGNED NULL,
    submitted_by BIGINT UNSIGNED NULL,
    submitted_at DATETIME NULL,
    approved_by BIGINT UNSIGNED NULL,
    approved_at DATETIME NULL,
    rejected_by BIGINT UNSIGNED NULL,
    rejected_at DATETIME NULL,
    rejection_reason TEXT NULL,
    posted_by BIGINT UNSIGNED NULL,
    posted_at DATETIME NULL,
    reversed_by BIGINT UNSIGNED NULL,
    reversed_at DATETIME NULL,
    cancelled_by BIGINT UNSIGNED NULL,
    cancelled_at DATETIME NULL,
    cancellation_reason TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    UNIQUE KEY uq_customer_payment(company_id, payment_number),
    CONSTRAINT fk_customer_payment_company FOREIGN KEY(company_id) REFERENCES companies(id),
    CONSTRAINT fk_customer_payment_customer FOREIGN KEY(customer_id) REFERENCES customers(id),
    CONSTRAINT fk_customer_payment_bank FOREIGN KEY(bank_account_id) REFERENCES bank_accounts(id),
    CONSTRAINT fk_customer_payment_cash_account FOREIGN KEY(cash_account_id) REFERENCES accounts(id),
    CONSTRAINT fk_customer_payment_journal FOREIGN KEY(journal_id) REFERENCES journals(id) ON DELETE SET NULL,
    CONSTRAINT fk_customer_payment_reversal_journal FOREIGN KEY(reversal_journal_id) REFERENCES journals(id) ON DELETE SET NULL,
    CONSTRAINT fk_customer_payment_created_by FOREIGN KEY(created_by) REFERENCES users(id),
    CONSTRAINT fk_customer_payment_updated_by FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_customer_payment_submitted_by FOREIGN KEY(submitted_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_customer_payment_approved_by FOREIGN KEY(approved_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_customer_payment_rejected_by FOREIGN KEY(rejected_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_customer_payment_posted_by FOREIGN KEY(posted_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_customer_payment_reversed_by FOREIGN KEY(reversed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_customer_payment_cancelled_by FOREIGN KEY(cancelled_by) REFERENCES users(id) ON DELETE SET NULL,
    CHECK(exchange_rate > 0),
    CHECK(amount > 0),
    CHECK(base_amount > 0),
    CHECK(unallocated_amount >= 0 AND unallocated_amount <= amount),
    INDEX idx_customer_payment_list(company_id, payment_date, status, customer_id),
    INDEX idx_customer_payment_reference(company_id, reference)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS customer_payment_allocations(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    customer_payment_id BIGINT UNSIGNED NOT NULL,
    sales_invoice_id BIGINT UNSIGNED NOT NULL,
    amount DECIMAL(20,2) NOT NULL,
    base_amount DECIMAL(20,2) NOT NULL,
    allocated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_customer_payment_allocation(customer_payment_id, sales_invoice_id),
    CONSTRAINT fk_customer_allocation_payment FOREIGN KEY(customer_payment_id) REFERENCES customer_payments(id) ON DELETE CASCADE,
    CONSTRAINT fk_customer_allocation_invoice FOREIGN KEY(sales_invoice_id) REFERENCES sales_invoices(id),
    CHECK(amount > 0),
    CHECK(base_amount > 0),
    INDEX idx_customer_allocation_invoice(sales_invoice_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)
}

async function createPurchaseReturnTables(db: MigrationDatabase) {
  await db.query(`CREATE TABLE IF NOT EXISTS purchase_returns(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    return_number VARCHAR(50) NOT NULL,
    return_date DATE NOT NULL,
    purchase_invoice_id BIGINT UNSIGNED NOT NULL,
    supplier_id BIGINT UNSIGNED NOT NULL,
    warehouse_id BIGINT UNSIGNED NULL,
    reference VARCHAR(100),
    currency CHAR(3) NOT NULL DEFAULT 'IDR',
    exchange_rate DECIMAL(20,8) NOT NULL DEFAULT 1,
    subtotal DECIMAL(20,2) NOT NULL DEFAULT 0,
    discount DECIMAL(20,2) NOT NULL DEFAULT 0,
    tax DECIMAL(20,2) NOT NULL DEFAULT 0,
    grand_total DECIMAL(20,2) NOT NULL DEFAULT 0,
    base_grand_total DECIMAL(20,2) NOT NULL DEFAULT 0,
    reason TEXT NOT NULL,
    status ENUM('draft','pending_approval','approved','posted','rejected','reversed','cancelled') NOT NULL DEFAULT 'draft',
    journal_id BIGINT UNSIGNED NULL,
    reversal_journal_id BIGINT UNSIGNED NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    updated_by BIGINT UNSIGNED NULL,
    submitted_by BIGINT UNSIGNED NULL,
    submitted_at DATETIME NULL,
    approved_by BIGINT UNSIGNED NULL,
    approved_at DATETIME NULL,
    rejected_by BIGINT UNSIGNED NULL,
    rejected_at DATETIME NULL,
    rejection_reason TEXT NULL,
    posted_by BIGINT UNSIGNED NULL,
    posted_at DATETIME NULL,
    reversed_by BIGINT UNSIGNED NULL,
    reversed_at DATETIME NULL,
    cancelled_by BIGINT UNSIGNED NULL,
    cancelled_at DATETIME NULL,
    cancellation_reason TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    UNIQUE KEY uq_purchase_return(company_id, return_number),
    CONSTRAINT fk_purchase_return_company FOREIGN KEY(company_id) REFERENCES companies(id),
    CONSTRAINT fk_purchase_return_invoice FOREIGN KEY(purchase_invoice_id) REFERENCES purchase_invoices(id),
    CONSTRAINT fk_purchase_return_supplier FOREIGN KEY(supplier_id) REFERENCES suppliers(id),
    CONSTRAINT fk_purchase_return_warehouse FOREIGN KEY(warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_purchase_return_journal FOREIGN KEY(journal_id) REFERENCES journals(id) ON DELETE SET NULL,
    CONSTRAINT fk_purchase_return_reversal_journal FOREIGN KEY(reversal_journal_id) REFERENCES journals(id) ON DELETE SET NULL,
    CONSTRAINT fk_purchase_return_created_by FOREIGN KEY(created_by) REFERENCES users(id),
    CONSTRAINT fk_purchase_return_updated_by FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_purchase_return_submitted_by FOREIGN KEY(submitted_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_purchase_return_approved_by FOREIGN KEY(approved_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_purchase_return_rejected_by FOREIGN KEY(rejected_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_purchase_return_posted_by FOREIGN KEY(posted_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_purchase_return_reversed_by FOREIGN KEY(reversed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_purchase_return_cancelled_by FOREIGN KEY(cancelled_by) REFERENCES users(id) ON DELETE SET NULL,
    CHECK(exchange_rate > 0),
    CHECK(grand_total >= 0),
    INDEX idx_purchase_return_list(company_id, return_date, status, supplier_id),
    INDEX idx_purchase_return_invoice(company_id, purchase_invoice_id, status)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS purchase_return_lines(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    purchase_return_id BIGINT UNSIGNED NOT NULL,
    purchase_invoice_line_id BIGINT UNSIGNED NOT NULL,
    line_number INT UNSIGNED NOT NULL,
    item_id BIGINT UNSIGNED NOT NULL,
    description VARCHAR(255),
    quantity DECIMAL(20,4) NOT NULL,
    unit_id BIGINT UNSIGNED NOT NULL,
    unit_price DECIMAL(20,4) NOT NULL,
    discount DECIMAL(20,2) NOT NULL DEFAULT 0,
    tax_code_id BIGINT UNSIGNED NULL,
    tax_rate DECIMAL(8,4) NOT NULL DEFAULT 0,
    tax_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    subtotal DECIMAL(20,2) NOT NULL,
    base_subtotal DECIMAL(20,2) NOT NULL,
    reason VARCHAR(255),
    inventory_movement_id BIGINT UNSIGNED NULL,
    UNIQUE KEY uq_purchase_return_line(purchase_return_id, line_number),
    CONSTRAINT fk_purchase_return_line_return FOREIGN KEY(purchase_return_id) REFERENCES purchase_returns(id) ON DELETE CASCADE,
    CONSTRAINT fk_purchase_return_line_invoice_line FOREIGN KEY(purchase_invoice_line_id) REFERENCES purchase_invoice_lines(id),
    CONSTRAINT fk_purchase_return_line_item FOREIGN KEY(item_id) REFERENCES items(id),
    CONSTRAINT fk_purchase_return_line_unit FOREIGN KEY(unit_id) REFERENCES units(id),
    CONSTRAINT fk_purchase_return_line_tax FOREIGN KEY(tax_code_id) REFERENCES tax_codes(id),
    CONSTRAINT fk_purchase_return_line_movement FOREIGN KEY(inventory_movement_id) REFERENCES inventory_movements(id) ON DELETE SET NULL,
    CHECK(quantity > 0),
    INDEX idx_purchase_return_line_invoice(purchase_invoice_line_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)
}

async function createSupplierPaymentTables(db: MigrationDatabase) {
  await db.query(`CREATE TABLE IF NOT EXISTS supplier_payments(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    payment_number VARCHAR(50) NOT NULL,
    payment_date DATE NOT NULL,
    supplier_id BIGINT UNSIGNED NOT NULL,
    bank_account_id BIGINT UNSIGNED NULL,
    cash_account_id BIGINT UNSIGNED NOT NULL,
    payment_method ENUM('cash','bank_transfer','check','card','other') NOT NULL,
    reference VARCHAR(100),
    currency CHAR(3) NOT NULL DEFAULT 'IDR',
    exchange_rate DECIMAL(20,8) NOT NULL DEFAULT 1,
    amount DECIMAL(20,2) NOT NULL,
    base_amount DECIMAL(20,2) NOT NULL,
    unallocated_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    notes TEXT,
    status ENUM('draft','pending_approval','approved','posted','rejected','reversed','cancelled') NOT NULL DEFAULT 'draft',
    journal_id BIGINT UNSIGNED NULL,
    reversal_journal_id BIGINT UNSIGNED NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    updated_by BIGINT UNSIGNED NULL,
    submitted_by BIGINT UNSIGNED NULL,
    submitted_at DATETIME NULL,
    approved_by BIGINT UNSIGNED NULL,
    approved_at DATETIME NULL,
    rejected_by BIGINT UNSIGNED NULL,
    rejected_at DATETIME NULL,
    rejection_reason TEXT NULL,
    posted_by BIGINT UNSIGNED NULL,
    posted_at DATETIME NULL,
    reversed_by BIGINT UNSIGNED NULL,
    reversed_at DATETIME NULL,
    cancelled_by BIGINT UNSIGNED NULL,
    cancelled_at DATETIME NULL,
    cancellation_reason TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    UNIQUE KEY uq_supplier_payment(company_id, payment_number),
    CONSTRAINT fk_supplier_payment_company FOREIGN KEY(company_id) REFERENCES companies(id),
    CONSTRAINT fk_supplier_payment_supplier FOREIGN KEY(supplier_id) REFERENCES suppliers(id),
    CONSTRAINT fk_supplier_payment_bank FOREIGN KEY(bank_account_id) REFERENCES bank_accounts(id),
    CONSTRAINT fk_supplier_payment_cash_account FOREIGN KEY(cash_account_id) REFERENCES accounts(id),
    CONSTRAINT fk_supplier_payment_journal FOREIGN KEY(journal_id) REFERENCES journals(id) ON DELETE SET NULL,
    CONSTRAINT fk_supplier_payment_reversal_journal FOREIGN KEY(reversal_journal_id) REFERENCES journals(id) ON DELETE SET NULL,
    CONSTRAINT fk_supplier_payment_created_by FOREIGN KEY(created_by) REFERENCES users(id),
    CONSTRAINT fk_supplier_payment_updated_by FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_supplier_payment_submitted_by FOREIGN KEY(submitted_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_supplier_payment_approved_by FOREIGN KEY(approved_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_supplier_payment_rejected_by FOREIGN KEY(rejected_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_supplier_payment_posted_by FOREIGN KEY(posted_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_supplier_payment_reversed_by FOREIGN KEY(reversed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_supplier_payment_cancelled_by FOREIGN KEY(cancelled_by) REFERENCES users(id) ON DELETE SET NULL,
    CHECK(exchange_rate > 0),
    CHECK(amount > 0),
    CHECK(base_amount > 0),
    CHECK(unallocated_amount >= 0 AND unallocated_amount <= amount),
    INDEX idx_supplier_payment_list(company_id, payment_date, status, supplier_id),
    INDEX idx_supplier_payment_reference(company_id, reference)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS supplier_payment_allocations(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    supplier_payment_id BIGINT UNSIGNED NOT NULL,
    purchase_invoice_id BIGINT UNSIGNED NOT NULL,
    amount DECIMAL(20,2) NOT NULL,
    base_amount DECIMAL(20,2) NOT NULL,
    allocated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_supplier_payment_allocation(supplier_payment_id, purchase_invoice_id),
    CONSTRAINT fk_supplier_allocation_payment FOREIGN KEY(supplier_payment_id) REFERENCES supplier_payments(id) ON DELETE CASCADE,
    CONSTRAINT fk_supplier_allocation_invoice FOREIGN KEY(purchase_invoice_id) REFERENCES purchase_invoices(id),
    CHECK(amount > 0),
    CHECK(base_amount > 0),
    INDEX idx_supplier_allocation_invoice(purchase_invoice_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)
}

async function createStockTransferTables(db: MigrationDatabase) {
  await db.query(`CREATE TABLE IF NOT EXISTS stock_transfers(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    transfer_number VARCHAR(50) NOT NULL,
    transfer_date DATE NOT NULL,
    from_warehouse_id BIGINT UNSIGNED NOT NULL,
    to_warehouse_id BIGINT UNSIGNED NOT NULL,
    reference VARCHAR(100),
    notes TEXT,
    status ENUM('draft','confirmed','posted','reversed','cancelled') NOT NULL DEFAULT 'draft',
    created_by BIGINT UNSIGNED NOT NULL,
    updated_by BIGINT UNSIGNED NULL,
    confirmed_by BIGINT UNSIGNED NULL,
    confirmed_at DATETIME NULL,
    posted_by BIGINT UNSIGNED NULL,
    posted_at DATETIME NULL,
    reversed_by BIGINT UNSIGNED NULL,
    reversed_at DATETIME NULL,
    cancelled_by BIGINT UNSIGNED NULL,
    cancelled_at DATETIME NULL,
    cancellation_reason TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    UNIQUE KEY uq_stock_transfer(company_id, transfer_number),
    CONSTRAINT fk_stock_transfer_company FOREIGN KEY(company_id) REFERENCES companies(id),
    CONSTRAINT fk_stock_transfer_from_warehouse FOREIGN KEY(from_warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_stock_transfer_to_warehouse FOREIGN KEY(to_warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_stock_transfer_created_by FOREIGN KEY(created_by) REFERENCES users(id),
    CONSTRAINT fk_stock_transfer_updated_by FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_stock_transfer_confirmed_by FOREIGN KEY(confirmed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_stock_transfer_posted_by FOREIGN KEY(posted_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_stock_transfer_reversed_by FOREIGN KEY(reversed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_stock_transfer_cancelled_by FOREIGN KEY(cancelled_by) REFERENCES users(id) ON DELETE SET NULL,
    CHECK(from_warehouse_id <> to_warehouse_id),
    INDEX idx_stock_transfer_list(company_id, transfer_date, status),
    INDEX idx_stock_transfer_warehouses(company_id, from_warehouse_id, to_warehouse_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS stock_transfer_lines(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    stock_transfer_id BIGINT UNSIGNED NOT NULL,
    line_number INT UNSIGNED NOT NULL,
    item_id BIGINT UNSIGNED NOT NULL,
    description VARCHAR(255),
    quantity DECIMAL(20,4) NOT NULL,
    unit_id BIGINT UNSIGNED NOT NULL,
    unit_cost DECIMAL(20,6) NOT NULL DEFAULT 0,
    out_movement_id BIGINT UNSIGNED NULL,
    in_movement_id BIGINT UNSIGNED NULL,
    UNIQUE KEY uq_stock_transfer_line(stock_transfer_id, line_number),
    CONSTRAINT fk_stock_transfer_line_transfer FOREIGN KEY(stock_transfer_id) REFERENCES stock_transfers(id) ON DELETE CASCADE,
    CONSTRAINT fk_stock_transfer_line_item FOREIGN KEY(item_id) REFERENCES items(id),
    CONSTRAINT fk_stock_transfer_line_unit FOREIGN KEY(unit_id) REFERENCES units(id),
    CONSTRAINT fk_stock_transfer_line_out_movement FOREIGN KEY(out_movement_id) REFERENCES inventory_movements(id) ON DELETE SET NULL,
    CONSTRAINT fk_stock_transfer_line_in_movement FOREIGN KEY(in_movement_id) REFERENCES inventory_movements(id) ON DELETE SET NULL,
    CHECK(quantity > 0),
    INDEX idx_stock_transfer_line_item(item_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)
}

async function createStockAdjustmentTables(db: MigrationDatabase) {
  await db.query(`CREATE TABLE IF NOT EXISTS stock_adjustments(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    adjustment_number VARCHAR(50) NOT NULL,
    adjustment_date DATE NOT NULL,
    warehouse_id BIGINT UNSIGNED NOT NULL,
    reason VARCHAR(255) NOT NULL,
    reference VARCHAR(100),
    notes TEXT,
    status ENUM('draft','pending_approval','approved','posted','rejected','reversed','cancelled') NOT NULL DEFAULT 'draft',
    journal_id BIGINT UNSIGNED NULL,
    reversal_journal_id BIGINT UNSIGNED NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    updated_by BIGINT UNSIGNED NULL,
    submitted_by BIGINT UNSIGNED NULL,
    submitted_at DATETIME NULL,
    approved_by BIGINT UNSIGNED NULL,
    approved_at DATETIME NULL,
    rejected_by BIGINT UNSIGNED NULL,
    rejected_at DATETIME NULL,
    rejection_reason TEXT NULL,
    posted_by BIGINT UNSIGNED NULL,
    posted_at DATETIME NULL,
    reversed_by BIGINT UNSIGNED NULL,
    reversed_at DATETIME NULL,
    cancelled_by BIGINT UNSIGNED NULL,
    cancelled_at DATETIME NULL,
    cancellation_reason TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    UNIQUE KEY uq_stock_adjustment(company_id, adjustment_number),
    CONSTRAINT fk_stock_adjustment_company FOREIGN KEY(company_id) REFERENCES companies(id),
    CONSTRAINT fk_stock_adjustment_warehouse FOREIGN KEY(warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_stock_adjustment_journal FOREIGN KEY(journal_id) REFERENCES journals(id) ON DELETE SET NULL,
    CONSTRAINT fk_stock_adjustment_reversal_journal FOREIGN KEY(reversal_journal_id) REFERENCES journals(id) ON DELETE SET NULL,
    CONSTRAINT fk_stock_adjustment_created_by FOREIGN KEY(created_by) REFERENCES users(id),
    CONSTRAINT fk_stock_adjustment_updated_by FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_stock_adjustment_submitted_by FOREIGN KEY(submitted_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_stock_adjustment_approved_by FOREIGN KEY(approved_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_stock_adjustment_rejected_by FOREIGN KEY(rejected_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_stock_adjustment_posted_by FOREIGN KEY(posted_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_stock_adjustment_reversed_by FOREIGN KEY(reversed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_stock_adjustment_cancelled_by FOREIGN KEY(cancelled_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_stock_adjustment_list(company_id, adjustment_date, status, warehouse_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS stock_adjustment_lines(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    stock_adjustment_id BIGINT UNSIGNED NOT NULL,
    line_number INT UNSIGNED NOT NULL,
    item_id BIGINT UNSIGNED NOT NULL,
    unit_id BIGINT UNSIGNED NOT NULL,
    system_quantity DECIMAL(20,4) NOT NULL,
    actual_quantity DECIMAL(20,4) NOT NULL,
    difference_quantity DECIMAL(20,4) NOT NULL,
    unit_cost DECIMAL(20,6) NOT NULL,
    value_difference DECIMAL(20,2) NOT NULL,
    gain_loss_account_id BIGINT UNSIGNED NOT NULL,
    reason VARCHAR(255),
    inventory_movement_id BIGINT UNSIGNED NULL,
    UNIQUE KEY uq_stock_adjustment_line(stock_adjustment_id, line_number),
    CONSTRAINT fk_stock_adjustment_line_adjustment FOREIGN KEY(stock_adjustment_id) REFERENCES stock_adjustments(id) ON DELETE CASCADE,
    CONSTRAINT fk_stock_adjustment_line_item FOREIGN KEY(item_id) REFERENCES items(id),
    CONSTRAINT fk_stock_adjustment_line_unit FOREIGN KEY(unit_id) REFERENCES units(id),
    CONSTRAINT fk_stock_adjustment_line_account FOREIGN KEY(gain_loss_account_id) REFERENCES accounts(id),
    CONSTRAINT fk_stock_adjustment_line_movement FOREIGN KEY(inventory_movement_id) REFERENCES inventory_movements(id) ON DELETE SET NULL,
    CHECK(actual_quantity >= 0),
    CHECK(difference_quantity = actual_quantity - system_quantity),
    INDEX idx_stock_adjustment_line_item(item_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)
}

async function down(db: MigrationDatabase) {
  await dropTables(db, [
    'stock_adjustment_lines',
    'stock_adjustments',
    'stock_transfer_lines',
    'stock_transfers',
    'supplier_payment_allocations',
    'supplier_payments',
    'purchase_return_lines',
    'purchase_returns',
    'customer_payment_allocations',
    'customer_payments',
    'sales_return_lines',
    'sales_returns',
    'purchase_invoice_receipts',
    'sales_invoice_deliveries',
  ])

  for (const [table, constraints, index, columns] of [
    [
      'purchase_invoice_lines',
      ['fk_purchase_invoice_line_receipt_line', 'fk_purchase_invoice_line_order_line'],
      null,
      ['goods_receipt_line_id', 'purchase_order_line_id'],
    ],
    [
      'sales_invoice_lines',
      ['fk_sales_invoice_line_delivery_line', 'fk_sales_invoice_line_order_line'],
      null,
      ['delivery_order_line_id', 'sales_order_line_id'],
    ],
    [
      'purchase_invoices',
      ['fk_purchase_invoice_goods_receipt', 'fk_purchase_invoice_purchase_order'],
      'idx_purchase_invoice_order',
      ['goods_receipt_id', 'purchase_order_id'],
    ],
    [
      'sales_invoices',
      ['fk_sales_invoice_delivery', 'fk_sales_invoice_sales_order'],
      'idx_sales_invoice_order',
      ['delivery_order_id', 'sales_order_id'],
    ],
  ] as const) {
    if (index) {
      await dropIndexIfExists(db, table, index)
    }
    for (const constraint of constraints) {
      await dropForeignKeyIfExists(db, table, constraint)
    }
    for (const column of columns) {
      await dropColumnIfExists(db, table, column)
    }
  }

  await dropTables(db, [
    'goods_receipt_lines',
    'goods_receipts',
    'purchase_order_lines',
    'purchase_orders',
    'delivery_order_lines',
    'delivery_orders',
    'sales_order_lines',
    'sales_orders',
  ])
}

export const migration = {
  name: '005_sales_purchase_inventory',
  up: async (db: MigrationDatabase) => {
    await createSalesOrderTables(db)
    await createDeliveryTables(db)
    await createPurchaseOrderTables(db)
    await createGoodsReceiptTables(db)
    await linkExistingInvoices(db)
    await createSalesReturnTables(db)
    await createCustomerPaymentTables(db)
    await createPurchaseReturnTables(db)
    await createSupplierPaymentTables(db)
    await createStockTransferTables(db)
    await createStockAdjustmentTables(db)
  },
  down,
}
