import { dropTables, type MigrationDatabase } from './helpers'

async function createRecurringJournalTables(db: MigrationDatabase) {
  await db.query(`CREATE TABLE IF NOT EXISTS recurring_journals(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    template_number VARCHAR(50) NOT NULL,
    name VARCHAR(191) NOT NULL,
    description TEXT,
    reference VARCHAR(100),
    frequency ENUM('monthly','quarterly','yearly','custom') NOT NULL,
    interval_value INT UNSIGNED NOT NULL DEFAULT 1,
    interval_unit ENUM('day','week','month','year') NULL,
    start_date DATE NOT NULL,
    next_run_date DATE NOT NULL,
    end_date DATE NULL,
    currency CHAR(3) NOT NULL DEFAULT 'IDR',
    exchange_rate DECIMAL(20,8) NOT NULL DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_generated_at DATETIME NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    UNIQUE KEY uq_recurring_journal(company_id, template_number),
    CONSTRAINT fk_recurring_journal_company FOREIGN KEY(company_id) REFERENCES companies(id),
    CONSTRAINT fk_recurring_journal_created_by FOREIGN KEY(created_by) REFERENCES users(id),
    CONSTRAINT fk_recurring_journal_updated_by FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL,
    CHECK(interval_value > 0),
    CHECK(exchange_rate > 0),
    INDEX idx_recurring_journal_due(company_id, is_active, next_run_date)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS recurring_journal_lines(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    recurring_journal_id BIGINT UNSIGNED NOT NULL,
    line_number INT UNSIGNED NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    description VARCHAR(255),
    cost_center_id BIGINT UNSIGNED NULL,
    project_id BIGINT UNSIGNED NULL,
    debit DECIMAL(20,2) NOT NULL DEFAULT 0,
    credit DECIMAL(20,2) NOT NULL DEFAULT 0,
    UNIQUE KEY uq_recurring_journal_line(recurring_journal_id, line_number),
    CONSTRAINT fk_recurring_line_template FOREIGN KEY(recurring_journal_id) REFERENCES recurring_journals(id) ON DELETE CASCADE,
    CONSTRAINT fk_recurring_line_account FOREIGN KEY(account_id) REFERENCES accounts(id),
    CONSTRAINT fk_recurring_line_cost_center FOREIGN KEY(cost_center_id) REFERENCES cost_centers(id),
    CONSTRAINT fk_recurring_line_project FOREIGN KEY(project_id) REFERENCES projects(id),
    CHECK(debit >= 0 AND credit >= 0),
    CHECK(NOT(debit > 0 AND credit > 0)),
    CHECK(debit > 0 OR credit > 0)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS recurring_journal_runs(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    recurring_journal_id BIGINT UNSIGNED NOT NULL,
    scheduled_date DATE NOT NULL,
    generated_journal_id BIGINT UNSIGNED NOT NULL,
    generated_by BIGINT UNSIGNED NULL,
    generated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_recurring_journal_run(recurring_journal_id, scheduled_date),
    UNIQUE KEY uq_recurring_generated_journal(generated_journal_id),
    CONSTRAINT fk_recurring_run_template FOREIGN KEY(recurring_journal_id) REFERENCES recurring_journals(id),
    CONSTRAINT fk_recurring_run_journal FOREIGN KEY(generated_journal_id) REFERENCES journals(id),
    CONSTRAINT fk_recurring_run_user FOREIGN KEY(generated_by) REFERENCES users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)
}

async function createApprovalTables(db: MigrationDatabase) {
  await db.query(`CREATE TABLE IF NOT EXISTS approval_rules(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(191) NOT NULL,
    transaction_type VARCHAR(50) NOT NULL,
    minimum_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    maximum_amount DECIMAL(20,2) NULL,
    currency CHAR(3) NOT NULL DEFAULT 'IDR',
    priority INT NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT UNSIGNED NOT NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_approval_rule(company_id, name),
    CONSTRAINT fk_approval_rule_company FOREIGN KEY(company_id) REFERENCES companies(id),
    CONSTRAINT fk_approval_rule_created_by FOREIGN KEY(created_by) REFERENCES users(id),
    CONSTRAINT fk_approval_rule_updated_by FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL,
    CHECK(minimum_amount >= 0),
    CHECK(maximum_amount IS NULL OR maximum_amount >= minimum_amount),
    INDEX idx_approval_rule_lookup(company_id, transaction_type, is_active, priority)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS approval_rule_steps(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    approval_rule_id BIGINT UNSIGNED NOT NULL,
    level_number SMALLINT UNSIGNED NOT NULL,
    role_id BIGINT UNSIGNED NULL,
    approver_user_id BIGINT UNSIGNED NULL,
    minimum_approvals SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_approval_rule_step(approval_rule_id, level_number),
    CONSTRAINT fk_approval_rule_step_rule FOREIGN KEY(approval_rule_id) REFERENCES approval_rules(id) ON DELETE CASCADE,
    CONSTRAINT fk_approval_rule_step_role FOREIGN KEY(role_id) REFERENCES roles(id),
    CONSTRAINT fk_approval_rule_step_user FOREIGN KEY(approver_user_id) REFERENCES users(id),
    CHECK(role_id IS NOT NULL OR approver_user_id IS NOT NULL),
    CHECK(minimum_approvals > 0)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS approval_requests(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    approval_rule_id BIGINT UNSIGNED NULL,
    transaction_type VARCHAR(50) NOT NULL,
    transaction_id BIGINT UNSIGNED NOT NULL,
    transaction_number VARCHAR(50) NOT NULL,
    transaction_date DATE NOT NULL,
    amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    currency CHAR(3) NOT NULL DEFAULT 'IDR',
    request_version INT UNSIGNED NOT NULL DEFAULT 1,
    current_level SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    status ENUM('pending','approved','rejected','cancelled') NOT NULL DEFAULT 'pending',
    submitted_by BIGINT UNSIGNED NOT NULL,
    submitted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at DATETIME NULL,
    comments TEXT NULL,
    UNIQUE KEY uq_approval_request(company_id, transaction_type, transaction_id, request_version),
    CONSTRAINT fk_approval_request_company FOREIGN KEY(company_id) REFERENCES companies(id),
    CONSTRAINT fk_approval_request_rule FOREIGN KEY(approval_rule_id) REFERENCES approval_rules(id) ON DELETE SET NULL,
    CONSTRAINT fk_approval_request_submitted_by FOREIGN KEY(submitted_by) REFERENCES users(id),
    CHECK(amount >= 0),
    INDEX idx_approval_request_queue(company_id, status, current_level, submitted_at),
    INDEX idx_approval_request_transaction(company_id, transaction_type, transaction_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS approval_steps(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    approval_request_id BIGINT UNSIGNED NOT NULL,
    level_number SMALLINT UNSIGNED NOT NULL,
    role_id BIGINT UNSIGNED NULL,
    approver_user_id BIGINT UNSIGNED NULL,
    status ENUM('pending','approved','rejected','skipped') NOT NULL DEFAULT 'pending',
    acted_by BIGINT UNSIGNED NULL,
    acted_at DATETIME NULL,
    comments TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_approval_request_step(approval_request_id, level_number),
    CONSTRAINT fk_approval_step_request FOREIGN KEY(approval_request_id) REFERENCES approval_requests(id) ON DELETE CASCADE,
    CONSTRAINT fk_approval_step_role FOREIGN KEY(role_id) REFERENCES roles(id),
    CONSTRAINT fk_approval_step_approver FOREIGN KEY(approver_user_id) REFERENCES users(id),
    CONSTRAINT fk_approval_step_acted_by FOREIGN KEY(acted_by) REFERENCES users(id) ON DELETE SET NULL,
    CHECK(role_id IS NOT NULL OR approver_user_id IS NOT NULL),
    INDEX idx_approval_step_queue(status, role_id, approver_user_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS approval_histories(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    approval_request_id BIGINT UNSIGNED NOT NULL,
    approval_step_id BIGINT UNSIGNED NULL,
    action ENUM('submitted','approved','rejected','cancelled','reassigned','commented') NOT NULL,
    from_status VARCHAR(30) NULL,
    to_status VARCHAR(30) NOT NULL,
    comments TEXT NULL,
    acted_by BIGINT UNSIGNED NOT NULL,
    acted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_approval_history_request FOREIGN KEY(approval_request_id) REFERENCES approval_requests(id) ON DELETE CASCADE,
    CONSTRAINT fk_approval_history_step FOREIGN KEY(approval_step_id) REFERENCES approval_steps(id) ON DELETE SET NULL,
    CONSTRAINT fk_approval_history_user FOREIGN KEY(acted_by) REFERENCES users(id),
    INDEX idx_approval_history_request(approval_request_id, acted_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)
}

async function createBankingTables(db: MigrationDatabase) {
  await db.query(`CREATE TABLE IF NOT EXISTS bank_statements(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    bank_account_id BIGINT UNSIGNED NOT NULL,
    statement_number VARCHAR(100) NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    opening_balance DECIMAL(20,2) NOT NULL,
    closing_balance DECIMAL(20,2) NOT NULL,
    status ENUM('draft','imported','reconciling','reconciled','closed') NOT NULL DEFAULT 'draft',
    import_file_name VARCHAR(255) NULL,
    import_checksum VARCHAR(128) NULL,
    imported_by BIGINT UNSIGNED NULL,
    imported_at DATETIME NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_bank_statement(company_id, bank_account_id, statement_number),
    CONSTRAINT fk_bank_statement_company FOREIGN KEY(company_id) REFERENCES companies(id),
    CONSTRAINT fk_bank_statement_account FOREIGN KEY(bank_account_id) REFERENCES bank_accounts(id),
    CONSTRAINT fk_bank_statement_imported_by FOREIGN KEY(imported_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_bank_statement_created_by FOREIGN KEY(created_by) REFERENCES users(id),
    CHECK(period_end >= period_start),
    INDEX idx_bank_statement_period(company_id, bank_account_id, period_start, period_end),
    INDEX idx_bank_statement_status(company_id, status)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS bank_statement_lines(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    bank_statement_id BIGINT UNSIGNED NOT NULL,
    line_number INT UNSIGNED NOT NULL,
    transaction_date DATE NOT NULL,
    description VARCHAR(500) NOT NULL,
    reference VARCHAR(191),
    debit DECIMAL(20,2) NOT NULL DEFAULT 0,
    credit DECIMAL(20,2) NOT NULL DEFAULT 0,
    balance DECIMAL(20,2) NOT NULL,
    external_id VARCHAR(191) NULL,
    reconciliation_status ENUM('unmatched','partial','matched','ignored') NOT NULL DEFAULT 'unmatched',
    matched_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    ignored_by BIGINT UNSIGNED NULL,
    ignored_at DATETIME NULL,
    ignore_reason VARCHAR(255) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_bank_statement_line(bank_statement_id, line_number),
    UNIQUE KEY uq_bank_statement_external(bank_statement_id, external_id),
    CONSTRAINT fk_bank_statement_line_statement FOREIGN KEY(bank_statement_id) REFERENCES bank_statements(id) ON DELETE CASCADE,
    CONSTRAINT fk_bank_statement_line_ignored_by FOREIGN KEY(ignored_by) REFERENCES users(id) ON DELETE SET NULL,
    CHECK(debit >= 0 AND credit >= 0),
    CHECK(NOT(debit > 0 AND credit > 0)),
    CHECK(debit > 0 OR credit > 0),
    CHECK(matched_amount >= 0),
    INDEX idx_bank_statement_line_match(bank_statement_id, reconciliation_status, transaction_date),
    INDEX idx_bank_statement_line_reference(reference)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS bank_reconciliations(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    reconciliation_number VARCHAR(50) NOT NULL,
    bank_account_id BIGINT UNSIGNED NOT NULL,
    bank_statement_id BIGINT UNSIGNED NOT NULL,
    reconciliation_date DATE NOT NULL,
    book_balance DECIMAL(20,2) NOT NULL,
    bank_balance DECIMAL(20,2) NOT NULL,
    reconciled_book_balance DECIMAL(20,2) NOT NULL DEFAULT 0,
    reconciled_bank_balance DECIMAL(20,2) NOT NULL DEFAULT 0,
    difference DECIMAL(20,2) NOT NULL,
    status ENUM('draft','completed','reopened') NOT NULL DEFAULT 'draft',
    notes TEXT,
    created_by BIGINT UNSIGNED NOT NULL,
    completed_by BIGINT UNSIGNED NULL,
    completed_at DATETIME NULL,
    reopened_by BIGINT UNSIGNED NULL,
    reopened_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_bank_reconciliation(company_id, reconciliation_number),
    UNIQUE KEY uq_bank_reconciliation_statement(bank_statement_id),
    CONSTRAINT fk_bank_reconciliation_company FOREIGN KEY(company_id) REFERENCES companies(id),
    CONSTRAINT fk_bank_reconciliation_account FOREIGN KEY(bank_account_id) REFERENCES bank_accounts(id),
    CONSTRAINT fk_bank_reconciliation_statement FOREIGN KEY(bank_statement_id) REFERENCES bank_statements(id),
    CONSTRAINT fk_bank_reconciliation_created_by FOREIGN KEY(created_by) REFERENCES users(id),
    CONSTRAINT fk_bank_reconciliation_completed_by FOREIGN KEY(completed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_bank_reconciliation_reopened_by FOREIGN KEY(reopened_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_bank_reconciliation_list(company_id, reconciliation_date, status, bank_account_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS bank_reconciliation_matches(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    bank_reconciliation_id BIGINT UNSIGNED NOT NULL,
    bank_statement_line_id BIGINT UNSIGNED NOT NULL,
    journal_line_id BIGINT UNSIGNED NOT NULL,
    matched_amount DECIMAL(20,2) NOT NULL,
    match_type ENUM('suggested','manual') NOT NULL,
    confidence_score DECIMAL(5,2) NULL,
    status ENUM('suggested','confirmed','rejected') NOT NULL DEFAULT 'suggested',
    confirmed_by BIGINT UNSIGNED NULL,
    confirmed_at DATETIME NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_bank_reconciliation_match(bank_reconciliation_id, bank_statement_line_id, journal_line_id),
    CONSTRAINT fk_bank_match_reconciliation FOREIGN KEY(bank_reconciliation_id) REFERENCES bank_reconciliations(id) ON DELETE CASCADE,
    CONSTRAINT fk_bank_match_statement_line FOREIGN KEY(bank_statement_line_id) REFERENCES bank_statement_lines(id),
    CONSTRAINT fk_bank_match_journal_line FOREIGN KEY(journal_line_id) REFERENCES journal_lines(id),
    CONSTRAINT fk_bank_match_confirmed_by FOREIGN KEY(confirmed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_bank_match_created_by FOREIGN KEY(created_by) REFERENCES users(id),
    CHECK(matched_amount > 0),
    CHECK(confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 100)),
    INDEX idx_bank_match_statement_line(bank_statement_line_id, status),
    INDEX idx_bank_match_journal_line(journal_line_id, status)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS cash_transfers(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    transfer_number VARCHAR(50) NOT NULL,
    transfer_date DATE NOT NULL,
    from_bank_account_id BIGINT UNSIGNED NULL,
    to_bank_account_id BIGINT UNSIGNED NULL,
    from_gl_account_id BIGINT UNSIGNED NOT NULL,
    to_gl_account_id BIGINT UNSIGNED NOT NULL,
    from_currency CHAR(3) NOT NULL DEFAULT 'IDR',
    to_currency CHAR(3) NOT NULL DEFAULT 'IDR',
    exchange_rate DECIMAL(20,8) NOT NULL DEFAULT 1,
    from_amount DECIMAL(20,2) NOT NULL,
    to_amount DECIMAL(20,2) NOT NULL,
    fee_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    fee_account_id BIGINT UNSIGNED NULL,
    reference VARCHAR(100),
    notes TEXT,
    status ENUM('draft','posted','reversed','cancelled') NOT NULL DEFAULT 'draft',
    journal_id BIGINT UNSIGNED NULL,
    reversal_journal_id BIGINT UNSIGNED NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    posted_by BIGINT UNSIGNED NULL,
    posted_at DATETIME NULL,
    reversed_by BIGINT UNSIGNED NULL,
    reversed_at DATETIME NULL,
    cancelled_by BIGINT UNSIGNED NULL,
    cancelled_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_cash_transfer(company_id, transfer_number),
    CONSTRAINT fk_cash_transfer_company FOREIGN KEY(company_id) REFERENCES companies(id),
    CONSTRAINT fk_cash_transfer_from_bank FOREIGN KEY(from_bank_account_id) REFERENCES bank_accounts(id),
    CONSTRAINT fk_cash_transfer_to_bank FOREIGN KEY(to_bank_account_id) REFERENCES bank_accounts(id),
    CONSTRAINT fk_cash_transfer_from_gl FOREIGN KEY(from_gl_account_id) REFERENCES accounts(id),
    CONSTRAINT fk_cash_transfer_to_gl FOREIGN KEY(to_gl_account_id) REFERENCES accounts(id),
    CONSTRAINT fk_cash_transfer_fee_account FOREIGN KEY(fee_account_id) REFERENCES accounts(id),
    CONSTRAINT fk_cash_transfer_journal FOREIGN KEY(journal_id) REFERENCES journals(id) ON DELETE SET NULL,
    CONSTRAINT fk_cash_transfer_reversal_journal FOREIGN KEY(reversal_journal_id) REFERENCES journals(id) ON DELETE SET NULL,
    CONSTRAINT fk_cash_transfer_created_by FOREIGN KEY(created_by) REFERENCES users(id),
    CONSTRAINT fk_cash_transfer_posted_by FOREIGN KEY(posted_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_cash_transfer_reversed_by FOREIGN KEY(reversed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_cash_transfer_cancelled_by FOREIGN KEY(cancelled_by) REFERENCES users(id) ON DELETE SET NULL,
    CHECK(from_gl_account_id <> to_gl_account_id),
    CHECK(exchange_rate > 0),
    CHECK(from_amount > 0 AND to_amount > 0),
    CHECK(fee_amount >= 0),
    INDEX idx_cash_transfer_list(company_id, transfer_date, status)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)
}

async function createFixedAssetTables(db: MigrationDatabase) {
  await db.query(`CREATE TABLE IF NOT EXISTS fixed_asset_categories(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    default_useful_life_months INT UNSIGNED NOT NULL,
    default_depreciation_method ENUM('straight_line') NOT NULL DEFAULT 'straight_line',
    asset_account_id BIGINT UNSIGNED NOT NULL,
    accumulated_depreciation_account_id BIGINT UNSIGNED NOT NULL,
    depreciation_expense_account_id BIGINT UNSIGNED NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_fixed_asset_category(company_id, code),
    CONSTRAINT fk_asset_category_company FOREIGN KEY(company_id) REFERENCES companies(id),
    CONSTRAINT fk_asset_category_asset_account FOREIGN KEY(asset_account_id) REFERENCES accounts(id),
    CONSTRAINT fk_asset_category_accum_account FOREIGN KEY(accumulated_depreciation_account_id) REFERENCES accounts(id),
    CONSTRAINT fk_asset_category_expense_account FOREIGN KEY(depreciation_expense_account_id) REFERENCES accounts(id),
    CHECK(default_useful_life_months > 0),
    INDEX idx_fixed_asset_category_active(company_id, is_active)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS fixed_assets(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    asset_code VARCHAR(50) NOT NULL,
    asset_name VARCHAR(191) NOT NULL,
    category_id BIGINT UNSIGNED NOT NULL,
    purchase_date DATE NOT NULL,
    in_service_date DATE NOT NULL,
    purchase_cost DECIMAL(20,2) NOT NULL,
    salvage_value DECIMAL(20,2) NOT NULL DEFAULT 0,
    useful_life_months INT UNSIGNED NOT NULL,
    depreciation_method ENUM('straight_line') NOT NULL DEFAULT 'straight_line',
    asset_account_id BIGINT UNSIGNED NOT NULL,
    accumulated_depreciation_account_id BIGINT UNSIGNED NOT NULL,
    depreciation_expense_account_id BIGINT UNSIGNED NOT NULL,
    accumulated_depreciation DECIMAL(20,2) NOT NULL DEFAULT 0,
    book_value DECIMAL(20,2) NOT NULL,
    location VARCHAR(191),
    serial_number VARCHAR(100),
    reference VARCHAR(100),
    notes TEXT,
    status ENUM('draft','active','fully_depreciated','disposed','inactive') NOT NULL DEFAULT 'draft',
    disposal_date DATE NULL,
    disposal_amount DECIMAL(20,2) NULL,
    disposal_journal_id BIGINT UNSIGNED NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    UNIQUE KEY uq_fixed_asset(company_id, asset_code),
    CONSTRAINT fk_fixed_asset_company FOREIGN KEY(company_id) REFERENCES companies(id),
    CONSTRAINT fk_fixed_asset_category FOREIGN KEY(category_id) REFERENCES fixed_asset_categories(id),
    CONSTRAINT fk_fixed_asset_asset_account FOREIGN KEY(asset_account_id) REFERENCES accounts(id),
    CONSTRAINT fk_fixed_asset_accum_account FOREIGN KEY(accumulated_depreciation_account_id) REFERENCES accounts(id),
    CONSTRAINT fk_fixed_asset_expense_account FOREIGN KEY(depreciation_expense_account_id) REFERENCES accounts(id),
    CONSTRAINT fk_fixed_asset_disposal_journal FOREIGN KEY(disposal_journal_id) REFERENCES journals(id) ON DELETE SET NULL,
    CONSTRAINT fk_fixed_asset_created_by FOREIGN KEY(created_by) REFERENCES users(id),
    CONSTRAINT fk_fixed_asset_updated_by FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL,
    CHECK(purchase_cost > 0),
    CHECK(salvage_value >= 0 AND salvage_value <= purchase_cost),
    CHECK(useful_life_months > 0),
    CHECK(accumulated_depreciation >= 0),
    CHECK(book_value >= 0),
    INDEX idx_fixed_asset_list(company_id, status, category_id),
    INDEX idx_fixed_asset_service_date(company_id, in_service_date)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS asset_depreciations(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    fixed_asset_id BIGINT UNSIGNED NOT NULL,
    accounting_period_id BIGINT UNSIGNED NOT NULL,
    depreciation_date DATE NOT NULL,
    opening_book_value DECIMAL(20,2) NOT NULL,
    depreciation_amount DECIMAL(20,2) NOT NULL,
    accumulated_depreciation DECIMAL(20,2) NOT NULL,
    closing_book_value DECIMAL(20,2) NOT NULL,
    status ENUM('draft','posted','reversed') NOT NULL DEFAULT 'draft',
    journal_id BIGINT UNSIGNED NULL,
    reversal_journal_id BIGINT UNSIGNED NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    posted_by BIGINT UNSIGNED NULL,
    posted_at DATETIME NULL,
    reversed_by BIGINT UNSIGNED NULL,
    reversed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_asset_depreciation(fixed_asset_id, accounting_period_id),
    CONSTRAINT fk_depreciation_company FOREIGN KEY(company_id) REFERENCES companies(id),
    CONSTRAINT fk_depreciation_asset FOREIGN KEY(fixed_asset_id) REFERENCES fixed_assets(id),
    CONSTRAINT fk_depreciation_period FOREIGN KEY(accounting_period_id) REFERENCES accounting_periods(id),
    CONSTRAINT fk_depreciation_journal FOREIGN KEY(journal_id) REFERENCES journals(id) ON DELETE SET NULL,
    CONSTRAINT fk_depreciation_reversal_journal FOREIGN KEY(reversal_journal_id) REFERENCES journals(id) ON DELETE SET NULL,
    CONSTRAINT fk_depreciation_created_by FOREIGN KEY(created_by) REFERENCES users(id),
    CONSTRAINT fk_depreciation_posted_by FOREIGN KEY(posted_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_depreciation_reversed_by FOREIGN KEY(reversed_by) REFERENCES users(id) ON DELETE SET NULL,
    CHECK(depreciation_amount > 0),
    CHECK(closing_book_value >= 0),
    INDEX idx_asset_depreciation_period(company_id, accounting_period_id, status)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)
}

async function createBudgetTables(db: MigrationDatabase) {
  await db.query(`CREATE TABLE IF NOT EXISTS budgets(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    budget_number VARCHAR(50) NOT NULL,
    name VARCHAR(191) NOT NULL,
    fiscal_year SMALLINT UNSIGNED NOT NULL,
    version_number INT UNSIGNED NOT NULL DEFAULT 1,
    currency CHAR(3) NOT NULL DEFAULT 'IDR',
    notes TEXT,
    status ENUM('draft','submitted','approved','rejected','locked') NOT NULL DEFAULT 'draft',
    created_by BIGINT UNSIGNED NOT NULL,
    updated_by BIGINT UNSIGNED NULL,
    submitted_by BIGINT UNSIGNED NULL,
    submitted_at DATETIME NULL,
    approved_by BIGINT UNSIGNED NULL,
    approved_at DATETIME NULL,
    rejected_by BIGINT UNSIGNED NULL,
    rejected_at DATETIME NULL,
    rejection_reason TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_budget_number(company_id, budget_number),
    UNIQUE KEY uq_budget_version(company_id, fiscal_year, version_number),
    CONSTRAINT fk_budget_company FOREIGN KEY(company_id) REFERENCES companies(id),
    CONSTRAINT fk_budget_created_by FOREIGN KEY(created_by) REFERENCES users(id),
    CONSTRAINT fk_budget_updated_by FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_budget_submitted_by FOREIGN KEY(submitted_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_budget_approved_by FOREIGN KEY(approved_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_budget_rejected_by FOREIGN KEY(rejected_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_budget_list(company_id, fiscal_year, status)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS budget_lines(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    budget_id BIGINT UNSIGNED NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    month TINYINT UNSIGNED NOT NULL,
    cost_center_id BIGINT UNSIGNED NULL,
    project_id BIGINT UNSIGNED NULL,
    dimension_key VARCHAR(191) NOT NULL DEFAULT 'none',
    amount DECIMAL(20,2) NOT NULL,
    notes VARCHAR(255),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_budget_line(budget_id, account_id, month, dimension_key),
    CONSTRAINT fk_budget_line_budget FOREIGN KEY(budget_id) REFERENCES budgets(id) ON DELETE CASCADE,
    CONSTRAINT fk_budget_line_account FOREIGN KEY(account_id) REFERENCES accounts(id),
    CONSTRAINT fk_budget_line_cost_center FOREIGN KEY(cost_center_id) REFERENCES cost_centers(id),
    CONSTRAINT fk_budget_line_project FOREIGN KEY(project_id) REFERENCES projects(id),
    CHECK(month BETWEEN 1 AND 12),
    INDEX idx_budget_line_dimensions(account_id, cost_center_id, project_id, month)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)
}

async function createClosingTables(db: MigrationDatabase) {
  await db.query(`CREATE TABLE IF NOT EXISTS period_close_runs(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    accounting_period_id BIGINT UNSIGNED NOT NULL,
    run_number INT UNSIGNED NOT NULL DEFAULT 1,
    requested_status ENUM('soft_closed','closed') NOT NULL,
    status ENUM('draft','validating','failed','validated','completed') NOT NULL DEFAULT 'draft',
    notes TEXT,
    initiated_by BIGINT UNSIGNED NOT NULL,
    validated_by BIGINT UNSIGNED NULL,
    validated_at DATETIME NULL,
    completed_by BIGINT UNSIGNED NULL,
    completed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_period_close_run(accounting_period_id, run_number),
    CONSTRAINT fk_period_close_company FOREIGN KEY(company_id) REFERENCES companies(id),
    CONSTRAINT fk_period_close_period FOREIGN KEY(accounting_period_id) REFERENCES accounting_periods(id),
    CONSTRAINT fk_period_close_initiated_by FOREIGN KEY(initiated_by) REFERENCES users(id),
    CONSTRAINT fk_period_close_validated_by FOREIGN KEY(validated_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_period_close_completed_by FOREIGN KEY(completed_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_period_close_status(company_id, accounting_period_id, status)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS period_close_checks(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    period_close_run_id BIGINT UNSIGNED NOT NULL,
    check_code ENUM('ar_reconciled','ap_reconciled','inventory_reconciled','bank_reconciled','depreciation_posted','recurring_journals_reviewed','trial_balance_balanced') NOT NULL,
    status ENUM('pending','passed','failed','waived') NOT NULL DEFAULT 'pending',
    is_blocking BOOLEAN NOT NULL DEFAULT TRUE,
    subledger_amount DECIMAL(20,2) NULL,
    general_ledger_amount DECIMAL(20,2) NULL,
    difference DECIMAL(20,2) NULL,
    evidence JSON NULL,
    details TEXT NULL,
    checked_by BIGINT UNSIGNED NULL,
    checked_at DATETIME NULL,
    waived_by BIGINT UNSIGNED NULL,
    waived_at DATETIME NULL,
    waiver_reason TEXT NULL,
    UNIQUE KEY uq_period_close_check(period_close_run_id, check_code),
    CONSTRAINT fk_period_check_run FOREIGN KEY(period_close_run_id) REFERENCES period_close_runs(id) ON DELETE CASCADE,
    CONSTRAINT fk_period_check_checked_by FOREIGN KEY(checked_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_period_check_waived_by FOREIGN KEY(waived_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_period_check_status(period_close_run_id, status, is_blocking)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS year_end_closings(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    fiscal_year SMALLINT UNSIGNED NOT NULL,
    closing_date DATE NOT NULL,
    status ENUM('draft','validated','posted','reversed') NOT NULL DEFAULT 'draft',
    current_year_earnings DECIMAL(20,2) NOT NULL DEFAULT 0,
    current_year_earnings_account_id BIGINT UNSIGNED NOT NULL,
    retained_earnings_account_id BIGINT UNSIGNED NOT NULL,
    closing_journal_id BIGINT UNSIGNED NULL,
    retained_earnings_journal_id BIGINT UNSIGNED NULL,
    reversal_journal_id BIGINT UNSIGNED NULL,
    notes TEXT,
    created_by BIGINT UNSIGNED NOT NULL,
    validated_by BIGINT UNSIGNED NULL,
    validated_at DATETIME NULL,
    posted_by BIGINT UNSIGNED NULL,
    posted_at DATETIME NULL,
    reversed_by BIGINT UNSIGNED NULL,
    reversed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_year_end_closing(company_id, fiscal_year),
    CONSTRAINT fk_year_end_company FOREIGN KEY(company_id) REFERENCES companies(id),
    CONSTRAINT fk_year_end_current_earnings FOREIGN KEY(current_year_earnings_account_id) REFERENCES accounts(id),
    CONSTRAINT fk_year_end_retained_earnings FOREIGN KEY(retained_earnings_account_id) REFERENCES accounts(id),
    CONSTRAINT fk_year_end_closing_journal FOREIGN KEY(closing_journal_id) REFERENCES journals(id) ON DELETE SET NULL,
    CONSTRAINT fk_year_end_retained_journal FOREIGN KEY(retained_earnings_journal_id) REFERENCES journals(id) ON DELETE SET NULL,
    CONSTRAINT fk_year_end_reversal_journal FOREIGN KEY(reversal_journal_id) REFERENCES journals(id) ON DELETE SET NULL,
    CONSTRAINT fk_year_end_created_by FOREIGN KEY(created_by) REFERENCES users(id),
    CONSTRAINT fk_year_end_validated_by FOREIGN KEY(validated_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_year_end_posted_by FOREIGN KEY(posted_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_year_end_reversed_by FOREIGN KEY(reversed_by) REFERENCES users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)

  await db.query(`CREATE TABLE IF NOT EXISTS year_end_closing_lines(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    year_end_closing_id BIGINT UNSIGNED NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    closing_balance DECIMAL(20,2) NOT NULL,
    debit DECIMAL(20,2) NOT NULL DEFAULT 0,
    credit DECIMAL(20,2) NOT NULL DEFAULT 0,
    CONSTRAINT fk_year_end_line_closing FOREIGN KEY(year_end_closing_id) REFERENCES year_end_closings(id) ON DELETE CASCADE,
    CONSTRAINT fk_year_end_line_account FOREIGN KEY(account_id) REFERENCES accounts(id),
    UNIQUE KEY uq_year_end_closing_line(year_end_closing_id, account_id),
    CHECK(debit >= 0 AND credit >= 0),
    CHECK(NOT(debit > 0 AND credit > 0))
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`)
}

export const migration = {
  name: '006_finance_workflow_reporting',
  up: async (db: MigrationDatabase) => {
    await createRecurringJournalTables(db)
    await createApprovalTables(db)
    await createBankingTables(db)
    await createFixedAssetTables(db)
    await createBudgetTables(db)
    await createClosingTables(db)
  },
  down: async (db: MigrationDatabase) =>
    dropTables(db, [
      'year_end_closing_lines',
      'year_end_closings',
      'period_close_checks',
      'period_close_runs',
      'budget_lines',
      'budgets',
      'asset_depreciations',
      'fixed_assets',
      'fixed_asset_categories',
      'cash_transfers',
      'bank_reconciliation_matches',
      'bank_reconciliations',
      'bank_statement_lines',
      'bank_statements',
      'approval_histories',
      'approval_steps',
      'approval_requests',
      'approval_rule_steps',
      'approval_rules',
      'recurring_journal_runs',
      'recurring_journal_lines',
      'recurring_journals',
    ]),
}
