import { addColumnIfMissing, type MigrationDatabase } from './helpers'
export const migration={name:'049_payroll_automation',async up(db:MigrationDatabase){
 await addColumnIfMissing(db,'payroll_runs','proration_method',"ENUM('none','calendar','working_days') NOT NULL DEFAULT 'none'")
 await addColumnIfMissing(db,'payroll_runs','working_weekdays',"VARCHAR(20) NOT NULL DEFAULT '1,2,3,4,5'")
 await addColumnIfMissing(db,'payroll_runs','prorate_bpjs','BOOLEAN NOT NULL DEFAULT FALSE')
 for(const [key,definition] of Object.entries({employment_from:'DATE NULL',employment_to:'DATE NULL',paid_basic_salary:'DECIMAL(18,2) NOT NULL DEFAULT 0',paid_fixed_allowance:'DECIMAL(18,2) NOT NULL DEFAULT 0',proration_ratio:'DECIMAL(12,8) NOT NULL DEFAULT 1',eligible_days:'INT NOT NULL DEFAULT 0',period_days:'INT NOT NULL DEFAULT 0'}))await addColumnIfMissing(db,'payroll_entries',key,definition)
 await db.query('UPDATE payroll_entries e JOIN payroll_employees m ON m.id=e.employee_id SET e.employment_from=m.hire_date,e.employment_to=m.termination_date,e.paid_basic_salary=e.basic_salary,e.paid_fixed_allowance=e.fixed_allowance')
 await db.query('UPDATE payroll_entries e JOIN payroll_runs r ON r.id=e.run_id SET e.period_days=DAY(LAST_DAY(r.date_from)),e.eligible_days=DAY(LAST_DAY(r.date_from))')
 await db.query(`CREATE TABLE IF NOT EXISTS payroll_attendance_days(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,entry_id BIGINT UNSIGNED NOT NULL,attendance_date DATE NOT NULL,status ENUM('hadir','cuti','sakit','absen','libur') NOT NULL,overtime_hours DECIMAL(6,2) NOT NULL DEFAULT 0,notes VARCHAR(500) NULL,imported_by BIGINT UNSIGNED NOT NULL,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_attendance_day(entry_id,attendance_date),FOREIGN KEY(entry_id) REFERENCES payroll_entries(id) ON DELETE CASCADE)`)
 await db.query(`CREATE TABLE IF NOT EXISTS payroll_recurring_components(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,company_id BIGINT UNSIGNED NOT NULL,employee_id BIGINT UNSIGNED NOT NULL,component_id BIGINT UNSIGNED NOT NULL,amount DECIMAL(18,2) NOT NULL DEFAULT 0,effective_from DATE NOT NULL,effective_to DATE NULL,prorate BOOLEAN NOT NULL DEFAULT TRUE,is_active BOOLEAN NOT NULL DEFAULT TRUE,version INT NOT NULL DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY ix_recurring_period(company_id,effective_from),FOREIGN KEY(employee_id) REFERENCES payroll_employees(id),FOREIGN KEY(component_id) REFERENCES payroll_components(id))`)
 await addColumnIfMissing(db,'payroll_entry_components','recurring_assignment_id','BIGINT UNSIGNED NULL')
},async down(){throw new Error('Preserve payroll automation history')}}
