import type {MigrationDatabase} from './helpers'
export const migration={name:'053_platform_operations',async up(db:MigrationDatabase){
 await db.query(`CREATE TABLE IF NOT EXISTS platform_plans(code VARCHAR(30) PRIMARY KEY,name VARCHAR(100) NOT NULL,max_companies INT NOT NULL,max_users INT NOT NULL)`)
 await db.query("INSERT IGNORE INTO platform_plans VALUES('starter','Starter',1,5),('growth','Growth',5,25),('enterprise','Enterprise',25,100),('legacy','Existing / internal',1000,1000)")
 await db.query(`CREATE TABLE IF NOT EXISTS platform_customers(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(191) NOT NULL,legacy_company_id BIGINT UNSIGNED NULL UNIQUE,plan_code VARCHAR(30) NOT NULL,status ENUM('trial','active','suspended') NOT NULL DEFAULT 'trial',valid_until DATE NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,version INT NOT NULL DEFAULT 1,FOREIGN KEY(plan_code) REFERENCES platform_plans(code))`)
 await db.query(`CREATE TABLE IF NOT EXISTS platform_companies(company_id BIGINT UNSIGNED PRIMARY KEY,customer_id BIGINT UNSIGNED NOT NULL,industry VARCHAR(30) NOT NULL DEFAULT 'trading',opening_date DATE NULL,provision_key CHAR(36) NULL UNIQUE,created_by BIGINT UNSIGNED NULL,FOREIGN KEY(company_id) REFERENCES companies(id),FOREIGN KEY(customer_id) REFERENCES platform_customers(id))`)
 await db.query("INSERT IGNORE INTO platform_customers(name,legacy_company_id,plan_code,status) SELECT name,id,'legacy','active' FROM companies")
 await db.query('INSERT IGNORE INTO platform_companies(company_id,customer_id) SELECT c.legacy_company_id,c.id FROM platform_customers c WHERE c.legacy_company_id IS NOT NULL')
 await db.query(`CREATE TABLE IF NOT EXISTS platform_alert_acknowledgements(alert_key VARCHAR(100) NOT NULL,user_id BIGINT UNSIGNED NOT NULL,acknowledged_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(alert_key,user_id),FOREIGN KEY(user_id) REFERENCES users(id))`)
 await db.query(`CREATE TABLE IF NOT EXISTS auth_mfa(user_id BIGINT UNSIGNED PRIMARY KEY,secret_cipher TEXT NULL,pending_cipher TEXT NULL,pending_until DATETIME NULL,enabled BOOLEAN NOT NULL DEFAULT FALSE,last_counter BIGINT NOT NULL DEFAULT -1,failed_attempts INT NOT NULL DEFAULT 0,blocked_until DATETIME NULL,recovery_hashes JSON NULL,FOREIGN KEY(user_id) REFERENCES users(id))`)
},async down(){throw new Error('Preserve platform customer and security history')}}
