export const IMPORT_TYPES = [
  'customer',
  'supplier',
  'item',
  'chart_of_accounts',
  'opening_balance',
  'sales',
  'purchase',
  'journal',
  'inventory',
  'bank_statement',
] as const

export type ImportType = (typeof IMPORT_TYPES)[number]
export type ErrorPolicy = 'all_or_nothing' | 'valid_only'
export type ImportAs = 'draft' | 'submitted'

export interface ImportDefinition {
  type: ImportType
  label: string
  permission: `import.${ImportType}`
  requiredColumns: readonly string[]
  optionalColumns: readonly string[]
  supportsImportAs: boolean
  isAccounting: boolean
  defaultErrorPolicy: ErrorPolicy
  sample: Record<string, string | number | boolean>
}

const definition = (
  value: Omit<ImportDefinition, 'permission'>,
): ImportDefinition => ({ ...value, permission: `import.${value.type}` })

export const IMPORT_DEFINITIONS: Record<ImportType, ImportDefinition> = {
  customer: definition({
    type: 'customer',
    label: 'Customers',
    requiredColumns: ['customer_code', 'customer_name'],
    optionalColumns: [
      'email',
      'phone',
      'address',
      'city',
      'tax_number',
      'payment_term',
      'currency',
      'credit_limit',
      'receivable_account_code',
      'opening_balance',
      'opening_balance_date',
      'opening_balance_offset_account_code',
    ],
    supportsImportAs: false,
    isAccounting: false,
    defaultErrorPolicy: 'valid_only',
    sample: {
      customer_code: 'CUST-001',
      customer_name: 'PT Pelanggan Contoh',
      email: 'finance@pelanggan.co.id',
      phone: '0215550101',
      address: 'Jakarta',
      city: 'Jakarta',
      tax_number: '01.234.567.8-999.000',
      payment_term: 30,
      currency: 'IDR',
      credit_limit: 0,
      receivable_account_code: '110200',
      opening_balance: 0,
      opening_balance_date: '',
      opening_balance_offset_account_code: '',
    },
  }),
  supplier: definition({
    type: 'supplier',
    label: 'Suppliers',
    requiredColumns: ['supplier_code', 'supplier_name'],
    optionalColumns: [
      'email',
      'phone',
      'address',
      'city',
      'tax_number',
      'payment_term',
      'currency',
      'payable_account_code',
      'opening_balance',
      'opening_balance_date',
      'opening_balance_offset_account_code',
    ],
    supportsImportAs: false,
    isAccounting: false,
    defaultErrorPolicy: 'valid_only',
    sample: {
      supplier_code: 'SUP-001',
      supplier_name: 'PT Pemasok Contoh',
      email: 'finance@pemasok.co.id',
      phone: '0215550202',
      address: 'Jakarta',
      city: 'Jakarta',
      tax_number: '02.345.678.9-999.000',
      payment_term: 30,
      currency: 'IDR',
      payable_account_code: '210100',
      opening_balance: 0,
      opening_balance_date: '',
      opening_balance_offset_account_code: '',
    },
  }),
  item: definition({
    type: 'item',
    label: 'Items / Services',
    requiredColumns: ['item_code', 'item_name', 'item_type', 'unit'],
    optionalColumns: [
      'warehouse',
      'purchase_price',
      'selling_price',
      'opening_stock',
      'opening_stock_date',
      'minimum_stock',
      'description',
      'barcode',
      'sales_account_code',
      'inventory_account_code',
      'cogs_account_code',
      'purchase_account_code',
    ],
    supportsImportAs: false,
    isAccounting: false,
    defaultErrorPolicy: 'valid_only',
    sample: {
      item_code: 'ITEM-001',
      item_name: 'Barang Contoh',
      item_type: 'inventory',
      unit: 'PCS',
      warehouse: 'WH-01',
      purchase_price: 75000,
      selling_price: 100000,
      opening_stock: 0,
      opening_stock_date: '',
      minimum_stock: 10,
      description: '',
      barcode: '',
      sales_account_code: '410100',
      inventory_account_code: '120100',
      cogs_account_code: '510100',
      purchase_account_code: '510100',
    },
  }),
  chart_of_accounts: definition({
    type: 'chart_of_accounts',
    label: 'Chart of Accounts',
    requiredColumns: ['account_code', 'account_name', 'account_type', 'normal_balance'],
    optionalColumns: [
      'parent_code',
      'is_header',
      'is_posting',
      'allow_manual_journal',
      'cash_flow_category',
      'report_group',
    ],
    supportsImportAs: false,
    isAccounting: true,
    defaultErrorPolicy: 'all_or_nothing',
    sample: {
      account_code: '110100',
      account_name: 'Kas',
      account_type: 'asset',
      normal_balance: 'debit',
      parent_code: '110000',
      is_header: false,
      is_posting: true,
      allow_manual_journal: true,
      cash_flow_category: 'operating',
      report_group: 'Kas dan Setara Kas',
    },
  }),
  opening_balance: definition({
    type: 'opening_balance',
    label: 'Opening Balances',
    requiredColumns: ['as_of_date', 'account_code', 'debit', 'credit'],
    optionalColumns: ['reference', 'description'],
    supportsImportAs: false,
    isAccounting: true,
    defaultErrorPolicy: 'all_or_nothing',
    sample: {
      as_of_date: '2026-01-01',
      reference: 'OPEN-2026',
      description: 'Saldo awal kas',
      account_code: '110100',
      debit: 10000000,
      credit: 0,
    },
  }),
  sales: definition({
    type: 'sales',
    label: 'Sales Transactions',
    requiredColumns: [
      'transaction_date',
      'invoice_number',
      'customer_code',
      'item_code',
      'quantity',
      'unit_price',
      'discount',
      'tax_code',
      'warehouse',
      'due_date',
      'description',
    ],
    optionalColumns: [],
    supportsImportAs: true,
    isAccounting: true,
    defaultErrorPolicy: 'all_or_nothing',
    sample: {
      transaction_date: '2026-08-01',
      invoice_number: 'INV-001',
      customer_code: 'CUST-001',
      item_code: 'ITEM-001',
      quantity: 2,
      unit_price: 100000,
      discount: 0,
      tax_code: 'PPN11',
      warehouse: 'WH-01',
      due_date: '2026-08-31',
      description: 'Penjualan barang contoh',
    },
  }),
  purchase: definition({
    type: 'purchase',
    label: 'Purchase Transactions',
    requiredColumns: [
      'transaction_date',
      'invoice_number',
      'supplier_code',
      'item_code',
      'quantity',
      'unit_price',
      'discount',
      'tax_code',
      'warehouse',
      'due_date',
      'description',
    ],
    optionalColumns: [],
    supportsImportAs: true,
    isAccounting: true,
    defaultErrorPolicy: 'all_or_nothing',
    sample: {
      transaction_date: '2026-08-01',
      invoice_number: 'SUP-INV-001',
      supplier_code: 'SUP-001',
      item_code: 'ITEM-001',
      quantity: 5,
      unit_price: 75000,
      discount: 0,
      tax_code: 'PPN11',
      warehouse: 'WH-01',
      due_date: '2026-08-31',
      description: 'Pembelian barang contoh',
    },
  }),
  journal: definition({
    type: 'journal',
    label: 'General Journals',
    requiredColumns: [
      'journal_date',
      'reference',
      'description',
      'account_code',
      'debit',
      'credit',
      'cost_center',
      'project',
    ],
    optionalColumns: [],
    supportsImportAs: true,
    isAccounting: true,
    defaultErrorPolicy: 'all_or_nothing',
    sample: {
      journal_date: '2026-08-01',
      reference: 'JV-IMPORT-001',
      description: 'Beban sewa Agustus',
      account_code: '610100',
      debit: 5000000,
      credit: 0,
      cost_center: 'HO',
      project: '',
    },
  }),
  inventory: definition({
    type: 'inventory',
    label: 'Inventory / Stock Opening Balance',
    requiredColumns: ['as_of_date', 'item_code', 'warehouse', 'quantity', 'unit_cost'],
    optionalColumns: ['reference', 'description'],
    supportsImportAs: false,
    isAccounting: true,
    defaultErrorPolicy: 'all_or_nothing',
    sample: {
      as_of_date: '2026-01-01',
      reference: 'OPEN-STOCK-2026',
      item_code: 'ITEM-001',
      warehouse: 'WH-01',
      quantity: 100,
      unit_cost: 75000,
      description: 'Saldo awal persediaan',
    },
  }),
  bank_statement: definition({
    type: 'bank_statement',
    label: 'Bank Statements',
    requiredColumns: [
      'bank_account_code',
      'statement_number',
      'transaction_date',
      'description',
      'reference',
      'debit',
      'credit',
      'balance',
    ],
    optionalColumns: [],
    supportsImportAs: false,
    isAccounting: true,
    defaultErrorPolicy: 'all_or_nothing',
    sample: {
      bank_account_code: 'BANK-BCA',
      statement_number: 'BCA-2026-08',
      transaction_date: '2026-08-01',
      description: 'Transfer masuk pelanggan',
      reference: 'TRX-001',
      debit: 1000000,
      credit: 0,
      balance: 11000000,
    },
  }),
}

export const getImportDefinition = (type: ImportType) => IMPORT_DEFINITIONS[type]

export const allColumns = (definitionValue: ImportDefinition) => [
  ...definitionValue.requiredColumns,
  ...definitionValue.optionalColumns,
]
